const G=Glance,L=GlanceLocale,P=GlancePreferences,S=GlanceProviderStatus,I=GlanceIntelligence,$=s=>document.querySelector(s);let data={},providerStatus={},intelligenceFeed={},providerStatusOpen=false,providerAlertKey='',historyMeta={total:0,loaded:0,firstAt:null,lastAt:null,truncated:false,elapsedMs:0},settings={opacity:55,position:'bottom-right',enabled:true,theme:'dark',sound:true,volume:18,language:L.detect(),serviceOrder:P.SERVICES,hiddenServices:[]},extensionId='',extensionVersion='',connected=false,pipWindow=null,pipChrome=null,highlightTimer=null,theme='dark',language=L.detect(),soundDesired=true,adviceEnabled=true,adviceIndex=0,adviceItems=[],adviceTimer=null,adviceKey='',lifecycleTimer=null,volumeEditing=false,serviceControlsKey='',historyStatusText='',historyStatusAt=0,statusLogIndex=0;const navigationId=`${Date.now()}-${Math.random()}`;
try{extensionId=localStorage.getItem('glance-extension-id')||'';settings={...settings,...JSON.parse(localStorage.getItem('glance-settings')||'{}')};adviceEnabled=localStorage.getItem('token-advice')!=='off'}catch{}
try{soundDesired=localStorage.getItem('token-sound')!=='off'}catch{}
try{language=localStorage.getItem('token-language')||settings.language||L.detect()}catch{}L.setLanguage(language);
const internal=!!globalThis.chrome?.runtime?.id;
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',5000)}
async function rpc(message){if(internal)return chrome.runtime.sendMessage(message);if(!/^[a-p]{32}$/.test(extensionId)||!globalThis.chrome?.runtime?.sendMessage)throw Error(L.t('extensionRequired'));return new Promise((resolve,reject)=>chrome.runtime.sendMessage(extensionId,message,r=>{const e=chrome.runtime.lastError;if(e)reject(Error(L.t('extensionConnectFailed')));else if(r?.error)reject(Error(r.error));else resolve(r)}));}
function paintAdvice(advance=false){
 adviceItems=GlanceAdvice.build(data);if(advance)adviceIndex=(adviceIndex+1)%adviceItems.length;else adviceIndex=Math.min(adviceIndex,adviceItems.length-1);const item=adviceItems[adviceIndex],panel=$('#advisor');panel.hidden=!adviceEnabled;$('#advice-toggle').textContent=`✦ ${L.t('advice')} ${adviceEnabled?'ON':'OFF'}`;$('#advice-toggle').setAttribute('aria-pressed',String(adviceEnabled));if(!adviceEnabled)return;
 $('#advisor-service').textContent=item.service;$('#advisor-title').textContent=item.title;$('#advisor-title').title=item.title;$('#advisor-text').textContent=item.text;$('#advisor-text').title=item.text;$('#advisor-evidence').textContent=item.evidence;$('#advisor-evidence').title=item.evidence;const source=$('#advisor-source'),url=/^https:\/\//.test(item.url||'')?item.url:'';source.hidden=!url;if(url){source.href=url;source.textContent=L.t('sourceLink');source.title=[item.source,item.evidence].filter(Boolean).join(' · ')}panel.dataset.tone=item.tone;$('#advisor-dots').innerHTML=adviceItems.map((_,i)=>`<i class="${i===adviceIndex?'active':''}"></i>`).join('');const key=[item.id,item.title,item.text,item.evidence,item.url].join('|');if(key!==adviceKey){adviceKey=key;panel.classList.remove('is-changing');void panel.offsetWidth;panel.classList.add('is-changing')}
}
function startAdviceTimer(){clearInterval(adviceTimer);if(adviceEnabled)adviceTimer=setInterval(()=>paintAdvice(true),9000)}
function dateTime(t){if(!t)return L.t('dateMissing');const d=new Date(t),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`;}
function paintStatusLog(){const messages=[L.t('soundHelp'),historyStatusText||L.t('historyLoading')];statusLogIndex=Math.max(0,Math.min(statusLogIndex,messages.length-1));const node=$('#status-log-message');if(!node)return;node.textContent=messages[statusLogIndex];node.title=messages[statusLogIndex];$('#status-log-position').textContent=`${statusLogIndex+1} / ${messages.length}`;$('#status-prev').disabled=statusLogIndex===0;$('#status-next').disabled=statusLogIndex===messages.length-1;}
function paintHistoryStatus(totalMs=0,force=false){const now=Date.now();if(!force&&historyStatusAt&&now-historyStatusAt<60000)return;historyStatusAt=now;if(!historyMeta.loaded)historyStatusText=L.t('historyNoneStatus',{ms:Math.round(totalMs)});else{const loaded=historyMeta.loaded.toLocaleString(L.locale()),total=historyMeta.total.toLocaleString(L.locale()),count=historyMeta.truncated?(language==='ja'?`直近${loaded}件／保存${total}`:`${loaded} recent / ${total} stored`):loaded;historyStatusText=L.t('historyStatus',{from:dateTime(historyMeta.firstAt),to:dateTime(historyMeta.lastAt),count,ms:Math.round(totalMs),limit:historyMeta.truncated?L.t('limitNote'):''});}paintStatusLog();}
function render(){
 clearTimeout(highlightTimer);const deadline=G.changes.next();if(Number.isFinite(deadline))highlightTimer=setTimeout(render,Math.max(1,deadline-Date.now()));
 $('#cards').innerHTML=Object.entries(G.services).map(([id,p])=>{const s=data[id],w=s?.windows?.[0],weekly=s?.windows?.[1],v=G.percent(w?.remaining),color=v!==null&&v<=15?'#ff9a99':p.color;return `<article class="card" aria-busy="${G.updating(s)}" style="--color:${color}"><div class="card-head"><span class="service-mark ${id}-mark">${p.mark}</span><div class="service-title"><h2>${p.name}</h2><span class="plan">${G.escape(G.shownPlan(s?.plan))}</span></div><span class="badge">${G.escape(G.status(s))}</span></div><div class="gauge" role="img" aria-label="${G.escape(p.name+' '+G.label(w?.label)+' '+L.t('remaining',{value:G.value(v)}))}"><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="51"/><circle class="fill" cx="60" cy="60" r="51" stroke-dasharray="${(v??0)*3.2044} 320.44"/></svg><div class="gauge-value">${G.numeric(id,'window:'+w?.label,v===null?'—':Math.round(v))}${v===null?'':'<small>%</small>'}<span>${v===null?L.t('valueMissing'):L.t('remainingUsage',{value:''}).trim()}</span></div><div class="gauge-reset">${G.resetInside(w)}</div></div><div class="metric-label">${G.escape(G.label(w?.label)||(id==='chatgpt'?L.t('workCommon'):L.t('currentSession')))}</div><div class="track primary-track" aria-label="${G.escape((G.label(w?.label)||L.t('currentSession'))+' '+L.t('remaining',{value:G.value(v)}))}"><i style="width:${v??0}%"></i></div><div class="metric-row"><span>${G.escape(G.label(weekly?.label)||L.t('weeklyLimit'))}</span><span>${G.numeric(id,'window:'+weekly?.label,G.value(weekly?.remaining))}</span></div><div class="track"><i style="width:${G.percent(weekly?.remaining)??0}%"></i></div><p class="reset">${G.escape(G.displayText(weekly?.reset||L.t('resetMissing')))}${G.resetSuffix(weekly)}</p><p class="card-note">${G.escape(id==='chatgpt'?L.t('normalChatUnavailable'):G.displayText(s?.note||L.t('officialConnect')))}</p>${G.extras(data,id)}${G.historyBox(s)}<div class="card-bottom"><span class="age">${G.escape(G.age(s))}</span><button data-service="${id}">${s?.status==='login'?L.t('loginOfficialButton'):s?L.t('openUsage'):L.t('connect')}</button></div></article>`}).join('');
 const cardNodes=[...$('#cards').querySelectorAll('.card')],allIds=Object.keys(G.services),visible=P.visible(settings);$('#cards').replaceChildren(...visible.map(id=>cardNodes[allIds.indexOf(id)]));$('#cards').dataset.count=String(visible.length);if(!visible.length){const empty=document.createElement('p');empty.className='cards-empty';empty.textContent=L.t('noServices');$('#cards').append(empty)}G.decorate($('#cards'),data,settings);
 $('#intelligence-main').innerHTML=I.view(intelligenceFeed,language,providerStatusOpen);$('#provider-status-main').innerHTML=S.view(providerStatus,language,providerStatusOpen);$('#widget').innerHTML=G.widget(data,settings,providerStatus,providerStatusOpen,intelligenceFeed);G.decorate($('#widget'),data,settings);$('#widget').className='widget '+settings.position;$('#widget').style.setProperty('--alpha',settings.opacity/100);$('#widget').style.display=settings.enabled?'':'none';
 if(pipWindow&&!pipWindow.closed){const widget=pipWindow.document.querySelector('.widget');if(widget){const openHistory=new Set([...widget.querySelectorAll('.widget-history[open]')].map(node=>node.dataset.historyId));widget.innerHTML=G.widget(data,settings,providerStatus,providerStatusOpen,intelligenceFeed);for(const node of widget.querySelectorAll('.widget-history'))node.open=openHistory.has(node.dataset.historyId);G.decorate(widget,data,settings);widget.style.setProperty('--alpha',settings.opacity/100)}pipWindow.document.documentElement.dataset.theme=theme;pipWindow.document.documentElement.dataset.language=language;pipWindow.document.body.style.setProperty('--alpha',settings.opacity/100);pipChrome?.update()}
 const versionMismatch=connected&&extensionVersion&&extensionVersion!==G.APP_VERSION;$('#connection').classList.toggle('connected',connected);$('#connection').classList.toggle('version-warning',versionMismatch);$('#connection').innerHTML=connected?(versionMismatch?`<span class="notice-icon">⚠︎</span><strong>${L.t('versionUpdate')}</strong><span class="notice-copy">${G.escape(L.t('versionDetail',{extension:extensionVersion,app:G.APP_VERSION}))}</span><span class="badge">VERSION</span>`:`<span class="notice-icon">↗</span><strong>${L.t('readyBrowser')}</strong><span class="notice-copy">${L.t('autoUpdate')}</span><span class="badge">LOCAL</span>`):`<span class="notice-icon">↗</span><div><strong>${L.t('connectTitle')}</strong><p>${L.t('connectBody')}</p></div><a href="#setup" class="button primary">${L.t('connectHow')}</a>`;
 paintAdvice();
}
document.addEventListener('click',event=>{if(event.target.closest('.provider-status > summary, .intelligence-feed > summary'))providerStatusOpen=!providerStatusOpen});
async function sync(){const started=performance.now();try{const r=await rpc({type:'GET'});if(!r)throw Error(L.t('connectFailed'));data=r.data||{};GlanceApiCredits.set(r.apiCredits);const previouslyRecovered=Object.values(providerStatus).some(row=>row.state==='recovered');providerStatus=S.normalize(r.providerStatus);intelligenceFeed=I.normalize(r.intelligenceFeed);const key=S.incidentKey(providerStatus);if(key&&key!==providerAlertKey)providerStatusOpen=true;const recovered=Object.values(providerStatus).some(row=>row.state==='recovered');if(recovered&&!previouslyRecovered)providerStatusOpen=true;providerAlertKey=key;historyMeta=r.historyMeta||historyMeta;extensionVersion=String(r.extensionVersion||'');G.observe(data);settings=P.normalize({...settings,...r.settings,volume:volumeEditing?settings.volume:r.settings?.volume??settings.volume});theme=settings.theme||theme;language=settings.language||language;L.setLanguage(language);soundDesired=settings.sound!==false;connected=true;applyControls();applyTheme();paintLanguage();paintSound(soundDesired,false);render();paintHistoryStatus(performance.now()-started)}catch{connected=false;extensionVersion='';render();paintHistoryStatus(performance.now()-started)}}
function paintServiceControls(){const order=P.order(settings.serviceOrder),hidden=P.hidden(settings.hiddenServices),key=[...order,...hidden,language].join('|'),node=$('#service-list');if(key===serviceControlsKey)return;serviceControlsKey=key;node.innerHTML=order.map((id,index)=>`<div class="service-choice"><label><input type="checkbox" data-visible="${id}" ${hidden.includes(id)?'':'checked'}><span>${G.services[id].name}</span></label><div class="service-move"><button type="button" data-move="${id}" data-step="-1" aria-label="${G.escape(L.t('moveUp',{service:G.services[id].name}))}" ${index===0?'disabled':''}>↑</button><button type="button" data-move="${id}" data-step="1" aria-label="${G.escape(L.t('moveDown',{service:G.services[id].name}))}" ${index===order.length-1?'disabled':''}>↓</button></div></div>`).join('');}
function applyControls(){$('#opacity').value=settings.opacity;$('#opacity-value').textContent=settings.opacity+'%';$('#position').value=settings.position;$('#enabled').checked=settings.enabled;if(!volumeEditing)$('#sound-volume').value=settings.volume??18;$('#sound-volume-value').textContent=(settings.volume??18)+'%';paintServiceControls()}
async function saveSettings(){settings=P.normalize({opacity:Number($('#opacity').value),position:$('#position').value,enabled:$('#enabled').checked,theme,language,sound:soundDesired,volume:Number($('#sound-volume').value),serviceOrder:settings.serviceOrder,hiddenServices:settings.hiddenServices});try{localStorage.setItem('glance-settings',JSON.stringify(settings));localStorage.setItem('token-language',language)}catch{}if(!settings.enabled&&pipWindow&&!pipWindow.closed)pipWindow.close();applyControls();render();if(connected)try{await rpc({type:'SETTINGS',settings})}catch(e){toast(e.message)}}
$('#cards').addEventListener('click',async e=>{const id=e.target.closest('[data-service]')?.dataset.service;if(!id)return;if(!connected){toast(L.t('installAndConnect'));$('#setup').scrollIntoView({behavior:'smooth'});return}try{await rpc({type:'OPEN',service:id});toast(L.t('officialOpened'));setTimeout(sync,2500)}catch(e){toast(e.message)}});
$('#status-prev').onclick=()=>{statusLogIndex=Math.max(0,statusLogIndex-1);paintStatusLog()};$('#status-next').onclick=()=>{statusLogIndex=Math.min(1,statusLogIndex+1);paintStatusLog()};
$('#refresh').onclick=async()=>{try{await rpc({type:'REFRESH'});toast(L.t('refreshed'));await sync()}catch(e){toast(e.message)}};
$('#connect-form').onsubmit=async e=>{e.preventDefault();extensionId=$('#extension-id').value.trim();try{const r=await rpc({type:'GET'});if(!r)throw Error(L.t('connectFailed'));localStorage.setItem('glance-extension-id',extensionId);await sync();toast(L.t('connectedToast'))}catch(e){toast(e.message)}};
$('#extension-id').value=extensionId;$('#opacity').oninput=saveSettings;$('#position').onchange=saveSettings;$('#enabled').onchange=saveSettings;
$('#service-list').addEventListener('change',e=>{const id=e.target.dataset.visible;if(!id)return;const hidden=new Set(P.hidden(settings.hiddenServices));if(e.target.checked)hidden.delete(id);else hidden.add(id);settings.hiddenServices=[...hidden];saveSettings()});
$('#service-list').addEventListener('click',e=>{const button=e.target.closest('[data-move]');if(!button)return;const order=P.order(settings.serviceOrder),index=order.indexOf(button.dataset.move),other=index+Number(button.dataset.step);if(index<0||other<0||other>=order.length)return;[order[index],order[other]]=[order[other],order[index]];settings.serviceOrder=order;saveSettings();$('#service-list [data-move="'+button.dataset.move+'"][data-step="'+button.dataset.step+'"]').focus()});
$('#advice-toggle').onclick=()=>{adviceEnabled=!adviceEnabled;try{localStorage.setItem('token-advice',adviceEnabled?'on':'off')}catch{}paintAdvice();startAdviceTimer()};$('#advisor-next').onclick=()=>{paintAdvice(true);startAdviceTimer()};$('#advisor').addEventListener('mouseenter',()=>clearInterval(adviceTimer));$('#advisor').addEventListener('mouseleave',startAdviceTimer);
async function openFrontmost(){if(!('documentPictureInPicture'in window))throw Error(language==='ja'?'このブラウザは最前面固定に対応していません':'This browser does not support always-on-top mode');if(pipWindow&&!pipWindow.closed){pipWindow.focus();return}pipWindow=await window.documentPictureInPicture.requestWindow({width:190,height:720});for(const name of ['style.css','style-v151.css','style-v152.css','style-v153.css','style-v160.css','style-v161.css','style-v162.css','style-v163.css','style-v164.css','style-v1140.css','style-v1150.css','style-v1160.css','style-v1170.css','style-v1171.css','style-v1180.css','style-v1190.css','style-v1210.css']){const link=pipWindow.document.createElement('link');link.rel='stylesheet';link.href=new URL(name,location.href).href;pipWindow.document.head.append(link)}pipWindow.document.title=L.t('appTitle');pipWindow.document.documentElement.dataset.theme=theme;pipWindow.document.documentElement.dataset.language=language;pipWindow.document.body.className='pip-body';pipWindow.document.body.style.setProperty('--alpha',settings.opacity/100);pipChrome=GlanceFloatingChrome.mount(pipWindow,true);const panel=pipWindow.document.createElement('div');panel.className='widget';panel.style.setProperty('--alpha',settings.opacity/100);panel.innerHTML=G.widget(data,settings,providerStatus,providerStatusOpen,intelligenceFeed);pipWindow.document.body.append(panel);pipWindow.document.addEventListener('click',event=>{if(event.target.closest('.provider-status > summary, .intelligence-feed > summary'))providerStatusOpen=!providerStatusOpen});pipWindow.addEventListener('pagehide',()=>{pipWindow=null;pipChrome=null},{once:true});if(connected)try{await rpc({type:'CLOSE_FLOAT'})}catch{}}
$('#pip').onclick=async()=>{try{await openFrontmost();toast(L.t('pipOpened'))}catch(e){if(connected)try{await rpc({type:'FLOAT'});toast(L.t('popupFallback'));return}catch{}toast(e.message)}};
$('#floating-normal').onclick=async()=>{if(!connected){toast(L.t('popupRequiresExtension'));return}if(pipWindow&&!pipWindow.closed)pipWindow.close();try{await rpc({type:'FLOAT'});toast(L.t('popupOpened'))}catch(e){toast(e.message)}};
if(internal)$('#setup').style.display='none';
async function announceLifecycle(type){if(!connected&&type!=='MONITOR_READY')return;try{await rpc({type,navigationId})}catch{}}
applyControls();paintLanguage();render();sync().then(()=>announceLifecycle('MONITOR_READY'));startAdviceTimer();setInterval(sync,2000);

function paintSound(on,waiting=false){$('#sound-toggle').innerHTML=`<span class="sound-dot"></span>${L.t('sound')} ${on?'ON':'OFF'}${waiting?(language==='ja'?' · 操作待ち':' · Waiting for interaction'):''}`;$('#sound-toggle').setAttribute('aria-pressed',String(on))}
const notifier=GlanceSound.createNotifier({active:()=>!connected&&G.changes.active(),eventId:()=>G.changes.eventId(),alertLevel:()=>G.changes.alertLevel(),onState:on=>paintSound(soundDesired,!on&&soundDesired&&!connected)});
paintSound(soundDesired,false);
async function armSound(){if(!soundDesired||notifier.isEnabled())return;try{await notifier.enable()}catch(e){paintSound(true,true)}}
function rememberSound(){settings.sound=soundDesired;try{localStorage.setItem('token-sound',soundDesired?'on':'off')}catch{}}
$('#sound-toggle').onclick=async()=>{soundDesired=!soundDesired;rememberSound();if(!soundDesired){notifier.disable();paintSound(false)}else{paintSound(true,false);try{await notifier.enable()}catch(e){if(!connected)toast(e.message)}}await saveSettings()};
const firstGesture=e=>{if(e.target.closest('#sound-toggle,#sound-test'))return;armSound();document.removeEventListener('pointerdown',firstGesture,true);document.removeEventListener('keydown',firstGesture,true)};
document.addEventListener('pointerdown',firstGesture,true);document.addEventListener('keydown',firstGesture,true);
window.addEventListener('pagehide',()=>{notifier.disable();clearTimeout(lifecycleTimer);announceLifecycle('MONITOR_CLOSED')});

$('#sound-test').onclick=async()=>{soundDesired=true;rememberSound();try{await notifier.test();paintSound(true);toast(L.t('soundPlayed'))}catch(e){toast(e.message)}};
$('#sound-volume').oninput=()=>{volumeEditing=true;settings.volume=Number($('#sound-volume').value);$('#sound-volume-value').textContent=settings.volume+'%';notifier.setVolume(settings.volume/100)};
$('#sound-volume').onchange=()=>{volumeEditing=false;saveSettings()};
$('#sound-volume').onblur=()=>{if(volumeEditing){volumeEditing=false;saveSettings()}};

try{theme=localStorage.getItem('token-theme')||settings.theme||'dark'}catch{}
function applyTheme(){document.documentElement.dataset.theme=theme;$('#theme-toggle').textContent=theme==='dark'?`☼ ${L.t('standard')}`:`◐ ${L.t('dark')}`;$('#theme-toggle').setAttribute('aria-pressed',String(theme==='dark'))}
$('#theme-toggle').onclick=async()=>{theme=theme==='dark'?'standard':'dark';settings.theme=theme;try{localStorage.setItem('token-theme',theme)}catch{}applyTheme();await saveSettings()};applyTheme();
function paintLanguage(){L.setLanguage(language);document.documentElement.lang=language;document.documentElement.dataset.language=language;document.title=L.t('appTitle');for(const node of document.querySelectorAll('[data-i18n]'))node.textContent=L.t(node.dataset.i18n);for(const option of document.querySelectorAll('#position option[data-i18n]'))option.textContent=L.t(option.dataset.i18n);$('#language-toggle').textContent=L.t('languageLabel');$('#extension-id').placeholder=L.t('extensionId');$('#extension-id').setAttribute('aria-label',L.t('extensionId'));$('#cards').setAttribute('aria-label',L.t('cardsAria'));$('#service-list').setAttribute('aria-label',L.t('serviceListAria'));$('#sound-volume').setAttribute('aria-label',L.t('volumeAria'));$('#sound-volume').parentElement.title=L.t('volumeAria');$('#sound-test').title=L.t('test');$('#advisor-next').title=L.t('adviceNext');$('#advisor-next').setAttribute('aria-label',L.t('adviceNext'));$('#status-log').setAttribute('aria-label',L.t('statusLogAria'));$('#status-prev').setAttribute('aria-label',L.t('statusPrevious'));$('#status-next').setAttribute('aria-label',L.t('statusNext'));paintStatusLog();applyTheme();paintFullscreen();paintSound(soundDesired,false);paintAdvice();}
$('#language-toggle').onclick=async()=>{language=language==='ja'?'en':'ja';settings.language=language;L.setLanguage(language);adviceKey='';try{localStorage.setItem('token-language',language)}catch{}paintLanguage();render();paintHistoryStatus(historyMeta.elapsedMs||0,true);await saveSettings()};
function paintFullscreen(){const on=!!document.fullscreenElement;$('#fullscreen').textContent=`⛶ ${on?L.t('exitFullscreen'):L.t('fullscreen')}`;$('#fullscreen').setAttribute('aria-pressed',String(on))}
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(e){toast(L.t('fullscreenFailed'))}};document.addEventListener('fullscreenchange',paintFullscreen);paintFullscreen();

$('#api-setup').onclick=async()=>{try{await rpc({type:'API_CREDITS_SETUP'})}catch(e){toast(e.message)}};
