const G=Glance,$=s=>document.querySelector(s);let data={},historyMeta={total:0,loaded:0,firstAt:null,lastAt:null,truncated:false,elapsedMs:0},settings={opacity:55,position:'bottom-right',enabled:true,theme:'dark',sound:true,volume:18},extensionId='',extensionVersion='',connected=false,pipWindow=null,highlightTimer=null,theme='dark',soundDesired=true,adviceEnabled=true,adviceIndex=0,adviceItems=[],adviceTimer=null,adviceKey='';
try{extensionId=localStorage.getItem('glance-extension-id')||'';settings={...settings,...JSON.parse(localStorage.getItem('glance-settings')||'{}')};adviceEnabled=localStorage.getItem('token-advice')!=='off'}catch{}
try{soundDesired=localStorage.getItem('token-sound')!=='off'}catch{}
const internal=!!globalThis.chrome?.runtime?.id;
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',5000)}
async function rpc(message){if(internal)return chrome.runtime.sendMessage(message);if(!/^[a-p]{32}$/.test(extensionId)||!globalThis.chrome?.runtime?.sendMessage)throw Error('拡張機能の接続が必要です');return new Promise((resolve,reject)=>chrome.runtime.sendMessage(extensionId,message,r=>{const e=chrome.runtime.lastError;if(e)reject(Error('拡張機能に接続できません。IDとブラウザを確認してください。'));else if(r?.error)reject(Error(r.error));else resolve(r)}));}
function paintAdvice(advance=false){
 adviceItems=GlanceAdvice.build(data);if(advance)adviceIndex=(adviceIndex+1)%adviceItems.length;else adviceIndex=Math.min(adviceIndex,adviceItems.length-1);const item=adviceItems[adviceIndex],panel=$('#advisor');panel.hidden=!adviceEnabled;$('#advice-toggle').textContent=`✦ アドバイス ${adviceEnabled?'ON':'OFF'}`;$('#advice-toggle').setAttribute('aria-pressed',String(adviceEnabled));if(!adviceEnabled)return;
 $('#advisor-service').textContent=item.service;$('#advisor-title').textContent=item.title;$('#advisor-title').title=item.title;$('#advisor-text').textContent=item.text;$('#advisor-text').title=item.text;$('#advisor-evidence').textContent=item.evidence;$('#advisor-evidence').title=item.evidence;panel.dataset.tone=item.tone;$('#advisor-dots').innerHTML=adviceItems.map((_,i)=>`<i class="${i===adviceIndex?'active':''}"></i>`).join('');const key=[item.id,item.title,item.text,item.evidence].join('|');if(key!==adviceKey){adviceKey=key;panel.classList.remove('is-changing');void panel.offsetWidth;panel.classList.add('is-changing')}
}
function startAdviceTimer(){clearInterval(adviceTimer);if(adviceEnabled)adviceTimer=setInterval(()=>paintAdvice(true),9000)}
function day(t){if(!t)return '日時未取得';const d=new Date(t),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`;}
function paintHistoryStatus(totalMs=0){const node=$('#history-status');if(!node)return;if(!historyMeta.loaded){node.textContent=`過去変化履歴はまだありません（読込・分析 ${Math.round(totalMs)}ms）`;return}const range=`${day(historyMeta.firstAt)}から${day(historyMeta.lastAt)}まで`,amount=historyMeta.truncated?`直近${historyMeta.loaded.toLocaleString('ja-JP')}件／保存${historyMeta.total.toLocaleString('ja-JP')}件`:`${historyMeta.loaded.toLocaleString('ja-JP')}件`;node.textContent=`${range}${amount}の過去変化履歴を取得しました（読込・分析 ${Math.round(totalMs)}ms${historyMeta.truncated?'・3秒上限':''}）`;}
function render(){
 clearTimeout(highlightTimer);const deadline=G.changes.next();if(Number.isFinite(deadline))highlightTimer=setTimeout(render,Math.max(1,deadline-Date.now()));
 $('#cards').innerHTML=Object.entries(G.services).map(([id,p])=>{const s=data[id],w=s?.windows?.[0],weekly=s?.windows?.[1],v=G.percent(w?.remaining),color=v!==null&&v<=15?'#ff9a99':p.color;return `<article class="card" aria-busy="${G.updating(s)}" style="--color:${color}"><div class="card-head"><span class="service-mark ${id}-mark">${p.mark}</span><div class="service-title"><h2>${p.name}</h2><span class="plan">${G.escape(s?.plan||'契約プラン未取得')}</span></div><span class="badge">${G.escape(G.status(s))}</span></div><div class="gauge" role="img" aria-label="${G.escape(p.name+' '+G.label(w?.label)+' 残り '+G.value(v))}"><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="51"/><circle class="fill" cx="60" cy="60" r="51" stroke-dasharray="${(v??0)*3.2044} 320.44"/></svg><div class="gauge-value">${G.numeric(id,'window:'+w?.label,v===null?'—':Math.round(v))}${v===null?'':'<small>%</small>'}<span>${v===null?'数値未取得':'残り使用量'}</span></div><div class="gauge-reset">${G.resetInside(w)}</div></div><div class="metric-label">${G.escape(G.label(w?.label)||(id==='chatgpt'?'Work / Codex 共通枠':'現在のセッション'))}</div><div class="track primary-track" aria-label="${G.escape((G.label(w?.label)||'現在のセッション')+' 残り '+G.value(v))}"><i style="width:${v??0}%"></i></div><div class="metric-row"><span>${G.escape(G.label(weekly?.label)||'週間の利用枠')}</span><span>${G.numeric(id,'window:'+weekly?.label,G.value(weekly?.remaining))}</span></div><div class="track"><i style="width:${G.percent(weekly?.remaining)??0}%"></i></div><p class="reset${G.resetUrgent(weekly)?' time-urgent':''}">${G.resetUrgent(weekly)?'<span aria-hidden="true">⚠︎ </span>':''}${G.escape(weekly?.reset||'リセット時刻未取得')}</p><p class="card-note">${G.escape(id==='chatgpt'?'通常のChat：取得不可（上記とは別枠）':s?.note||'公式の使用量画面に接続してください。')}</p>${G.extras(data,id)}${G.historyBox(s)}<div class="card-bottom"><span class="age">${G.escape(G.age(s))}</span><button data-service="${id}">${s?.status==='login'?'公式サイトでログイン':s?'使用量を開く':'接続'}</button></div></article>`}).join('');
 $('#widget').innerHTML=G.widget(data);$('#widget').className='widget '+settings.position;$('#widget').style.setProperty('--alpha',settings.opacity/100);$('#widget').style.display=settings.enabled?'':'none';
 if(pipWindow&&!pipWindow.closed){const widget=pipWindow.document.querySelector('.widget');if(widget){widget.innerHTML=G.widget(data);widget.style.setProperty('--alpha',settings.opacity/100)}pipWindow.document.documentElement.dataset.theme=theme}
 const versionMismatch=connected&&extensionVersion&&extensionVersion!==G.APP_VERSION;$('#connection').classList.toggle('connected',connected);$('#connection').classList.toggle('version-warning',versionMismatch);$('#connection').innerHTML=connected?(versionMismatch?`<span class="notice-icon">⚠︎</span><strong>拡張機能の更新が必要</strong><span class="notice-copy">拡張機能 v${G.escape(extensionVersion)} ／ 画面 v${G.escape(G.APP_VERSION)}。新しいZIPへ更新して再読み込みしてください。</span><span class="badge">VERSION</span>`:'<span class="notice-icon">↗</span><strong>ブラウザに接続済み</strong><span class="notice-copy">60秒ごとに公式セッションを自動更新</span><span class="badge">LOCAL</span>'):'<span class="notice-icon">↗</span><div><strong>ブラウザを接続して、モニターを開始</strong><p>拡張機能が公式の使用量画面を読み取ります。ログイン情報は公式画面で入力してください。</p></div><a href="#setup" class="button primary">接続方法</a>';
 paintAdvice();
}
async function sync(){const started=performance.now();try{const r=await rpc({type:'GET'});if(!r)throw Error('接続できません');data=r.data||{};historyMeta=r.historyMeta||historyMeta;extensionVersion=String(r.extensionVersion||'');G.observe(data);settings={...settings,...r.settings};theme=settings.theme||theme;soundDesired=settings.sound!==false;connected=true;applyControls();applyTheme();paintSound(soundDesired,false);render();paintHistoryStatus(performance.now()-started)}catch{connected=false;extensionVersion='';render();paintHistoryStatus(performance.now()-started)}}
function applyControls(){$('#opacity').value=settings.opacity;$('#opacity-value').textContent=settings.opacity+'%';$('#position').value=settings.position;$('#enabled').checked=settings.enabled;$('#sound-volume').value=settings.volume??18}
async function saveSettings(){settings={opacity:Number($('#opacity').value),position:$('#position').value,enabled:$('#enabled').checked,theme,sound:soundDesired,volume:Number($('#sound-volume').value)};try{localStorage.setItem('glance-settings',JSON.stringify(settings))}catch{}if(!settings.enabled&&pipWindow&&!pipWindow.closed)pipWindow.close();applyControls();render();if(connected)try{await rpc({type:'SETTINGS',settings})}catch(e){toast(e.message)}}
$('#cards').addEventListener('click',async e=>{const id=e.target.closest('[data-service]')?.dataset.service;if(!id)return;if(!connected){toast('拡張機能を追加し、接続してください');$('#setup').scrollIntoView({behavior:'smooth'});return}try{await rpc({type:'OPEN',service:id});toast('公式画面を開きました。未ログインならログインしてください。');setTimeout(sync,2500)}catch(e){toast(e.message)}});
$('#refresh').onclick=async()=>{try{await rpc({type:'REFRESH'});toast('公式サービスからバックグラウンド更新しました');await sync()}catch(e){toast(e.message)}};
$('#connect-form').onsubmit=async e=>{e.preventDefault();extensionId=$('#extension-id').value.trim();try{const r=await rpc({type:'GET'});if(!r)throw Error('接続できません');localStorage.setItem('glance-extension-id',extensionId);await sync();toast('接続しました')}catch(e){toast(e.message)}};
$('#extension-id').value=extensionId;$('#opacity').oninput=saveSettings;$('#position').onchange=saveSettings;$('#enabled').onchange=saveSettings;
$('#advice-toggle').onclick=()=>{adviceEnabled=!adviceEnabled;try{localStorage.setItem('token-advice',adviceEnabled?'on':'off')}catch{}paintAdvice();startAdviceTimer()};$('#advisor-next').onclick=()=>{paintAdvice(true);startAdviceTimer()};$('#advisor').addEventListener('mouseenter',()=>clearInterval(adviceTimer));$('#advisor').addEventListener('mouseleave',startAdviceTimer);
async function openFrontmost(){if(!('documentPictureInPicture'in window))throw Error('このブラウザは最前面固定に対応していません');if(pipWindow&&!pipWindow.closed){pipWindow.focus();return}pipWindow=await window.documentPictureInPicture.requestWindow({width:340,height:650});for(const name of ['style.css','style-v151.css']){const link=pipWindow.document.createElement('link');link.rel='stylesheet';link.href=new URL(name,location.href).href;pipWindow.document.head.append(link)}pipWindow.document.title='LLMs トークン残量モニタ · 最前面';pipWindow.document.documentElement.dataset.theme=theme;pipWindow.document.body.className='pip-body';const badge=pipWindow.document.createElement('div');badge.className='pip-pin';badge.innerHTML='<b>● 最前面固定</b><small>このモニタ画面を閉じると終了します</small>';const panel=pipWindow.document.createElement('div');panel.className='widget';panel.style.setProperty('--alpha',settings.opacity/100);panel.innerHTML=G.widget(data);pipWindow.document.body.append(badge,panel);pipWindow.addEventListener('pagehide',()=>{pipWindow=null},{once:true});if(connected)try{await rpc({type:'CLOSE_FLOAT'})}catch{}}
$('#pip').onclick=async()=>{try{await openFrontmost();toast('最前面固定のフローティング表示を開きました')}catch(e){if(connected)try{await rpc({type:'FLOAT'});toast('最前面固定に非対応のため通常小窓を開きました');return}catch{}toast(e.message)}};
$('#floating-normal').onclick=async()=>{if(!connected){toast('通常小窓には拡張機能の接続が必要です');return}if(pipWindow&&!pipWindow.closed)pipWindow.close();try{await rpc({type:'FLOAT'});toast('通常のフローティング小窓を開きました')}catch(e){toast(e.message)}};
if(internal)$('#setup').style.display='none';
applyControls();render();sync();startAdviceTimer();setInterval(sync,2000);

function paintSound(on,waiting=false){$('#sound-toggle').innerHTML=`<span class="sound-dot"></span>${on?'通知音 ON'+(waiting?' · 操作待ち':''):'通知音 OFF'}`;$('#sound-toggle').setAttribute('aria-pressed',String(on))}
const notifier=GlanceSound.createNotifier({active:()=>!connected&&G.changes.active(),eventId:()=>G.changes.eventId(),onState:on=>paintSound(soundDesired,!on&&soundDesired&&!connected)});
paintSound(soundDesired,false);
async function armSound(){if(!soundDesired||notifier.isEnabled())return;try{await notifier.enable()}catch(e){paintSound(true,true)}}
function rememberSound(){settings.sound=soundDesired;try{localStorage.setItem('token-sound',soundDesired?'on':'off')}catch{}}
$('#sound-toggle').onclick=async()=>{soundDesired=!soundDesired;rememberSound();if(!soundDesired){notifier.disable();paintSound(false)}else{paintSound(true,false);try{await notifier.enable()}catch(e){if(!connected)toast(e.message)}}await saveSettings()};
const firstGesture=e=>{if(e.target.closest('#sound-toggle,#sound-test'))return;armSound();document.removeEventListener('pointerdown',firstGesture,true);document.removeEventListener('keydown',firstGesture,true)};
document.addEventListener('pointerdown',firstGesture,true);document.addEventListener('keydown',firstGesture,true);
window.addEventListener('pagehide',()=>notifier.disable());

$('#sound-test').onclick=async()=>{soundDesired=true;rememberSound();try{await notifier.test();paintSound(true);toast('試聴音を再生しました。聞こえない場合は音量・タブのミュート・出力先を確認してください。')}catch(e){toast(e.message)}};
$('#sound-volume').oninput=()=>{notifier.setVolume(Number($('#sound-volume').value)/100);settings.volume=Number($('#sound-volume').value);saveSettings()};

try{theme=localStorage.getItem('token-theme')||settings.theme||'dark'}catch{}
function applyTheme(){document.documentElement.dataset.theme=theme;$('#theme-toggle').textContent=theme==='dark'?'☼ 標準':'◐ ダーク';$('#theme-toggle').setAttribute('aria-pressed',String(theme==='dark'))}
$('#theme-toggle').onclick=async()=>{theme=theme==='dark'?'standard':'dark';settings.theme=theme;try{localStorage.setItem('token-theme',theme)}catch{}applyTheme();await saveSettings()};applyTheme();
function paintFullscreen(){const on=!!document.fullscreenElement;$('#fullscreen').textContent=on?'⛶ 全画面を終了':'⛶ フルスクリーン';$('#fullscreen').setAttribute('aria-pressed',String(on))}
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(e){toast('フルスクリーン表示を開始できませんでした')}};document.addEventListener('fullscreenchange',paintFullscreen);paintFullscreen();
