importScripts('state.js','history.js','fetchers.js','notification-batch.js');
const URLS={chatgpt:'https://chatgpt.com/settings/usage?tab=overview',claude:'https://claude.ai/settings/usage',gemini:'https://gemini.google.com/usage'};
const HOSTS={chatgpt:'chatgpt.com',claude:'claude.ai',gemini:'gemini.google.com'};
const ALLOWED=new Set(['https://ai-usage-glance.ntusnog.chatgpt.site']);
const FETCHERS={chatgpt:()=>GlanceFetchers.fetchChatGPT(),claude:async()=>{const saved=await chrome.storage.local.get('claudeOrganizationId'),snapshot=await GlanceFetchers.fetchClaude(fetch,saved.claudeOrganizationId||'');if(snapshot.organizationId)await chrome.storage.local.set({claudeOrganizationId:snapshot.organizationId});return snapshot;},gemini:()=>GlanceFetchers.fetchGemini()};
let queue=Promise.resolve(),dataQueue=Promise.resolve(),historyQueue=Promise.resolve(),soundTimer=null,monitorCloseTimer=null,monitorNavigationId='',monitorTabId=null,historyViewCache={version:null,history:{},meta:{total:0,loaded:0,firstAt:null,lastAt:null,truncated:false,elapsedMs:0,limit:GlanceHistory.LOAD_LIMIT,budgetMs:2600}};
const environmentLanguage=()=>String(chrome.i18n.getUILanguage()||'').toLowerCase().startsWith('ja')?'ja':'en';
function serialize(fn){const result=queue.then(fn);queue=result.catch(()=>{});return result;}
function updateData(fn){const result=dataQueue.then(async()=>{const saved=await chrome.storage.local.get('data'),data=saved.data||{},value=await fn(data);await chrome.storage.local.set({data});return value});dataQueue=result.catch(()=>{});return result;}
async function state(){const saved=await chrome.storage.local.get(['data','history','historyVersion','settings']),data=saved.data||{},version=Number(saved.historyVersion)||0;if(historyViewCache.version!==version){const view=GlanceHistory.view(saved.history||{},{limit:GlanceHistory.LOAD_LIMIT,budgetMs:2600});historyViewCache={version,...view};}for(const[id,snapshot]of Object.entries(data))snapshot.history=historyViewCache.history[id]||{};return {extensionVersion:chrome.runtime.getManifest().version,settings:{opacity:55,position:'bottom-right',enabled:true,theme:'dark',sound:true,volume:18,language:environmentLanguage(),...saved.settings},data,historyMeta:historyViewCache.meta};}
function recordHistory(id,windows,capturedAt){const result=historyQueue.then(async()=>{const saved=await chrome.storage.local.get(['history','historyLast','historyVersion']),next=GlanceHistory.record(saved.history||{},saved.historyLast||{},id,windows,capturedAt),update={history:next.history,historyLast:next.last};if(next.changed)update.historyVersion=(Number(saved.historyVersion)||0)+1;await chrome.storage.local.set(update)});historyQueue=result.catch(()=>{});return result;}
function resetHistoryBaseline(id){const result=historyQueue.then(async()=>{const saved=await chrome.storage.local.get('historyLast'),last=saved.historyLast||{};delete last[id];await chrome.storage.local.set({historyLast:last})});historyQueue=result.catch(()=>{});return result;}
function numericChanged(old={},next={}){if(!old.capturedAt||next.status!=='ready')return false;for(const item of next.windows||[]){const before=old.windows?.find(w=>w.label===item.label);if(before&&before.remaining!==item.remaining)return true}for(const item of next.extras||[]){const before=old.extras?.find(e=>e.label===item.label),a=String(before?.value||'').match(/\d+(?:\.\d+)?/g)||[],b=String(item.value||'').match(/\d+(?:\.\d+)?/g)||[];if(before&&JSON.stringify(a)!==JSON.stringify(b))return true}return false;}
async function ensureOffscreen(){if(!chrome.offscreen)return false;const present=typeof chrome.offscreen.hasDocument==='function'?await chrome.offscreen.hasDocument():(await chrome.runtime.getContexts({contextTypes:['OFFSCREEN_DOCUMENT'],documentUrls:[chrome.runtime.getURL('offscreen.html')]})).length>0;if(present)return true;await chrome.offscreen.createDocument({url:'offscreen.html',reasons:['AUDIO_PLAYBACK'],justification:'Play three short local alerts when a usage number changes'});return true;}
function queueChangeSound(){clearTimeout(soundTimer);soundTimer=setTimeout(async()=>{const saved=await chrome.storage.local.get('settings'),settings={sound:true,volume:18,...saved.settings};if(settings.sound===false)return;try{if(await ensureOffscreen())await chrome.runtime.sendMessage({type:'PLAY_CHANGE_SOUND',volume:settings.volume})}catch{}},180);}
async function accept(id,incoming,notify=true){const now=Date.now();let changed=false,wasLogin=false;const snapshot=await updateData(data=>{const old=data[id]||{};changed=numericChanged(old,incoming);wasLogin=old.status!=='login'&&incoming.status==='login';const next=GlanceState.accept(old,incoming,now);data[id]=next;return next});if(wasLogin)await resetHistoryBaseline(id);if(snapshot.status==='ready')await recordHistory(id,snapshot.windows,now);if(changed&&notify)queueChangeSound();return {snapshot,changed};}
function timebox(promise,id,ms=25000){let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(`${id} update timeout`)),ms)})]).finally(()=>clearTimeout(timer));}
async function refreshService(id){await updateData(data=>{const snapshot=GlanceState.loading(data[id]);data[id]=snapshot;return snapshot});try{const result=await timebox(FETCHERS[id](),id);delete result.organizationId;return (await accept(id,{...result,source:'api'},false)).changed;}catch(error){if(error?.login)await accept(id,{status:'login',windows:[],extras:[],plan:'未取得',source:'api',note:'公式サイトでログインしてください。'},false);else await accept(id,{status:'unavailable',source:'api',note:'取得できませんでした。'},false);return false;}}
async function refresh(){const ids=Object.keys(FETCHERS),results=await Promise.allSettled(ids.map(refreshService));GlanceNotificationBatch.notifyOnce(results,queueChangeSound);return {ok:true,services:results.map((result,index)=>({service:ids[index],ok:result.status==='fulfilled'}))};}
async function openService(id){if(!URLS[id])throw Error('サービスが見つかりません');await chrome.tabs.create({url:URLS[id],active:true});return {ok:true};}
function floatingTab(win){const target=chrome.runtime.getURL('floating.html');return (win?.tabs||[]).some(tab=>tab.url===target||tab.pendingUrl===target);}
async function openFloating(focus=false){const settings={enabled:true,...(await chrome.storage.local.get('settings')).settings};if(settings.enabled===false)return {ok:false};const saved=await chrome.storage.local.get('floatingWindowId');if(saved.floatingWindowId)try{const win=await chrome.windows.get(saved.floatingWindowId,{populate:true});if(floatingTab(win)){if(focus)await chrome.windows.update(saved.floatingWindowId,{focused:true});return {ok:true};}}catch{}await chrome.storage.local.remove('floatingWindowId');const win=await chrome.windows.create({url:chrome.runtime.getURL('floating.html'),type:'popup',width:180,height:720,focused:focus});await chrome.storage.local.set({floatingWindowId:win.id});return {ok:true};}
async function closeFloating(){const saved=await chrome.storage.local.get('floatingWindowId');if(saved.floatingWindowId)try{await chrome.windows.remove(saved.floatingWindowId)}catch{}await chrome.storage.local.remove('floatingWindowId');}
async function monitorReady(navigationId,tabId){clearTimeout(monitorCloseTimer);const changed=monitorNavigationId&&monitorNavigationId!==navigationId;monitorNavigationId=String(navigationId||'');monitorTabId=Number.isInteger(tabId)?tabId:monitorTabId;const result=await openFloating(false);if(changed&&result.ok){const saved=await chrome.storage.local.get('floatingWindowId');if(saved.floatingWindowId)try{const win=await chrome.windows.get(saved.floatingWindowId,{populate:true}),tab=win.tabs?.find(item=>item.url===chrome.runtime.getURL('floating.html'));if(tab?.id)await chrome.tabs.reload(tab.id)}catch{}}return {ok:true};}
function monitorClosed(navigationId){if(String(navigationId||'')!==monitorNavigationId)return {ok:true};clearTimeout(monitorCloseTimer);monitorCloseTimer=setTimeout(()=>{monitorNavigationId='';monitorTabId=null;closeFloating()},1600);return {ok:true};}
async function removeStaleFloating(){const saved=await chrome.storage.local.get('floatingWindowId'),ids=new Set;try{for(const context of await chrome.runtime.getContexts({documentUrls:[chrome.runtime.getURL('floating.html')]})){if(!Number.isInteger(context.tabId))continue;try{const tab=await chrome.tabs.get(context.tabId);if(Number.isInteger(tab.windowId))ids.add(tab.windowId)}catch{}}}catch{}if(saved.floatingWindowId)try{const win=await chrome.windows.get(saved.floatingWindowId,{populate:true});if(floatingTab(win))ids.add(saved.floatingWindowId)}catch{}for(const id of ids)try{await chrome.windows.remove(id)}catch{}await chrome.storage.local.remove('floatingWindowId');}
async function handle(message,sender,external){
 if(!message||typeof message!=='object')throw Error('無効なリクエスト');const origin=(()=>{try{return new URL(sender.url).origin}catch{return ''}})(),trusted=external?ALLOWED.has(origin):sender.url?.startsWith(chrome.runtime.getURL(''));
 if(message.type==='SNAPSHOT'&&!external){const id=message.service;if(!HOSTS[id]||origin!==`https://${HOSTS[id]}`)return {ok:false};const windows=(message.windows||[]).filter(item=>typeof item.remaining==='number'&&Number.isFinite(item.remaining)&&item.remaining>=0&&item.remaining<=100).slice(0,6).map(item=>({label:String(item.label).slice(0,80),remaining:item.remaining,reset:String(item.reset||'').slice(0,150),resetAt:Number.isFinite(Number(item.resetAt))?Number(item.resetAt):null})),extras=(Array.isArray(message.extras)?message.extras:[]).slice(0,8).filter(item=>typeof item.label==='string'&&typeof item.value==='string').map(item=>({label:item.label.slice(0,80),value:item.value.slice(0,160),detail:String(item.detail||'').slice(0,180),expiresAt:Number.isFinite(Number(item.expiresAt))?Number(item.expiresAt):null,observedAt:Number.isFinite(Number(item.observedAt))?Number(item.observedAt):null,barPercent:Number.isFinite(Number(item.barPercent))?Math.max(0,Math.min(100,Number(item.barPercent))):null})),plan=typeof message.plan==='string'?message.plan.slice(0,80):'未取得';await accept(id,{windows,extras,plan,source:'dom',status:message.status==='login'?'login':windows.length||extras.length||plan!=='未取得'?'ready':'unavailable',note:message.status==='login'?'公式サイトでログインしてください。':'公式画面から取得。'});return {ok:true};}
 if(message.type==='GET'&&(!external||trusted))return state();if(message.type==='OPEN_CURRENT'&&!external&&HOSTS[message.service]&&origin===`https://${HOSTS[message.service]}`)return openService(message.service);if(!trusted)throw Error('このページからの操作は許可されていません');if(message.type==='MONITOR_READY')return monitorReady(message.navigationId,sender.tab?.id);if(message.type==='MONITOR_CLOSED')return monitorClosed(message.navigationId);if(message.type==='OPEN')return openService(message.service);if(message.type==='REFRESH')return refresh();if(message.type==='FLOAT')return openFloating(true);if(message.type==='CLOSE_FLOAT')return closeFloating();if(message.type==='SETTINGS'){const input=message.settings||{},prior={enabled:true,...(await chrome.storage.local.get('settings')).settings},settings={opacity:Math.min(100,Math.max(15,Number(input.opacity)||55)),position:['bottom-right','bottom-left','top-right','top-left'].includes(input.position)?input.position:'bottom-right',enabled:input.enabled!==false,theme:input.theme==='standard'?'standard':'dark',language:input.language==='en'?'en':'ja',sound:input.sound!==false,volume:Math.min(50,Math.max(1,Number(input.volume)||18))};await chrome.storage.local.set({settings});if(!settings.enabled)await closeFloating();else if(!prior.enabled)await openFloating(false);return {ok:true};}throw Error('未対応の操作');
}
function listener(external){return(message,sender,reply)=>{if(!external&&message?.type==='PLAY_CHANGE_SOUND')return false;const task=message?.type==='GET'?handle(message,sender,external):serialize(()=>handle(message,sender,external));task.then(reply,error=>reply({error:error.message}));return true;};}
async function bootstrap(){chrome.alarms.create('llms-refresh',{periodInMinutes:1});const saved=await chrome.storage.local.get(['settings','historyLast','historyVersion']);const updates={};if(!saved.settings)updates.settings={opacity:55,position:'bottom-right',enabled:true,theme:'dark',language:environmentLanguage(),sound:true,volume:18};else if(!saved.settings.language)updates.settings={...saved.settings,language:environmentLanguage()};if(!saved.historyLast)updates.historyLast={};if(!Number.isFinite(Number(saved.historyVersion)))updates.historyVersion=0;if(Object.keys(updates).length)await chrome.storage.local.set(updates);await removeStaleFloating();await openFloating(false);await refresh();}
chrome.runtime.onMessage.addListener(listener(false));chrome.runtime.onMessageExternal.addListener(listener(true));chrome.action.onClicked.addListener(()=>chrome.tabs.create({url:chrome.runtime.getURL('index.html')}));chrome.runtime.onInstalled.addListener(()=>serialize(bootstrap));chrome.runtime.onStartup.addListener(()=>serialize(bootstrap));chrome.alarms.onAlarm.addListener(alarm=>{if(alarm.name==='llms-refresh')serialize(refresh)});chrome.tabs.onRemoved.addListener(tabId=>{if(tabId===monitorTabId)monitorClosed(monitorNavigationId)});chrome.windows.onRemoved.addListener(async windowId=>{const saved=await chrome.storage.local.get('floatingWindowId');if(saved.floatingWindowId===windowId)await chrome.storage.local.remove('floatingWindowId');});
