importScripts('preferences.js','provider-status.js','intelligence.js','state.js','history.js','fetchers.js','notification-batch.js');
const URLS={chatgpt:'https://chatgpt.com/settings/usage?tab=overview',claude:'https://claude.ai/settings/usage',gemini:'https://gemini.google.com/usage'};
const HOSTS={chatgpt:'chatgpt.com',claude:'claude.ai',gemini:'gemini.google.com'};
const ALLOWED=new Set(['https://llmsmonitor.ntusnog.chatgpt.site']);
const DEFAULT_SETTINGS={opacity:55,position:'bottom-right',enabled:true,theme:'dark',sound:true,volume:18,serviceOrder:GlancePreferences.SERVICES,hiddenServices:[]};
const FETCHERS={chatgpt:()=>GlanceFetchers.fetchChatGPT(),claude:async()=>{const saved=await chrome.storage.local.get('claudeOrganizationId'),snapshot=await GlanceFetchers.fetchClaude(fetch,saved.claudeOrganizationId||'');if(snapshot.organizationId)await chrome.storage.local.set({claudeOrganizationId:snapshot.organizationId});return snapshot;},gemini:()=>GlanceFetchers.fetchGemini()};
let queue=Promise.resolve(),dataQueue=Promise.resolve(),historyQueue=Promise.resolve(),monitorCloseTimer=null,monitorNavigationId='',monitorTabId=null,historyViewCache={version:null,history:{},meta:{total:0,loaded:0,firstAt:null,lastAt:null,truncated:false,elapsedMs:0,limit:GlanceHistory.LOAD_LIMIT,budgetMs:2600}};
const environmentLanguage=()=>String(chrome.i18n.getUILanguage()||'').toLowerCase().startsWith('ja')?'ja':'en';
function serialize(fn){const result=queue.then(fn);queue=result.catch(()=>{});return result;}
function updateData(fn){const result=dataQueue.then(async()=>{const saved=await chrome.storage.local.get('data'),data=saved.data||{},value=await fn(data);await chrome.storage.local.set({data});return value});dataQueue=result.catch(()=>{});return result;}
async function state(){const saved=await chrome.storage.local.get(['data','history','historyVersion','settings','providerStatus','intelligenceFeed']),data=saved.data||{},version=Number(saved.historyVersion)||0;if(historyViewCache.version!==version){const view=GlanceHistory.view(saved.history||{},{limit:GlanceHistory.LOAD_LIMIT,budgetMs:2600});historyViewCache={version,...view};}for(const[id,snapshot]of Object.entries(data))snapshot.history=historyViewCache.history[id]||{};return {extensionVersion:chrome.runtime.getManifest().version,settings:GlancePreferences.normalize({...DEFAULT_SETTINGS,language:environmentLanguage(),...saved.settings}),data,providerStatus:GlanceProviderStatus.normalize(saved.providerStatus),intelligenceFeed:GlanceIntelligence.normalize(saved.intelligenceFeed),historyMeta:historyViewCache.meta};}
function recordHistory(id,windows,capturedAt){const result=historyQueue.then(async()=>{const saved=await chrome.storage.local.get(['history','historyLast','historyVersion']),next=GlanceHistory.record(saved.history||{},saved.historyLast||{},id,windows,capturedAt),update={history:next.history,historyLast:next.last};if(next.changed)update.historyVersion=(Number(saved.historyVersion)||0)+1;await chrome.storage.local.set(update)});historyQueue=result.catch(()=>{});return result;}
function resetHistoryBaseline(id){const result=historyQueue.then(async()=>{const saved=await chrome.storage.local.get('historyLast'),last=saved.historyLast||{};delete last[id];await chrome.storage.local.set({historyLast:last})});historyQueue=result.catch(()=>{});return result;}
function numericChanged(old={},next={}){if(!old.capturedAt||next.status!=='ready')return false;for(const item of next.windows||[]){const before=old.windows?.find(w=>w.label===item.label);if(before&&before.remaining!==item.remaining)return true}for(const item of next.extras||[]){const before=old.extras?.find(e=>e.label===item.label),a=String(before?.value||'').match(/\d+(?:\.\d+)?/g)||[],b=String(item.value||'').match(/\d+(?:\.\d+)?/g)||[];if(before&&JSON.stringify(a)!==JSON.stringify(b))return true}return false;}
async function ensureOffscreen(){if(!chrome.offscreen)return false;const present=typeof chrome.offscreen.hasDocument==='function'?await chrome.offscreen.hasDocument():(await chrome.runtime.getContexts({contextTypes:['OFFSCREEN_DOCUMENT'],documentUrls:[chrome.runtime.getURL('offscreen.html')]})).length>0;if(present)return true;await chrome.offscreen.createDocument({url:'offscreen.html',reasons:['AUDIO_PLAYBACK'],justification:'Play three short local alerts when a usage number changes'});return true;}
async function playChangeSound(){const saved=await chrome.storage.local.get('settings'),settings={sound:true,volume:18,...saved.settings};if(settings.sound===false)return false;try{if(await ensureOffscreen()){await chrome.runtime.sendMessage({type:'PLAY_CHANGE_SOUND',volume:settings.volume});return true}}catch{}return false;}
async function statusJson(url){const signal=AbortSignal.timeout(8000),response=await fetch(url,{credentials:'omit',cache:'no-store',signal,headers:{accept:'application/json'}});if(!response.ok||new URL(response.url).origin!==new URL(url).origin)throw Error('Status source unavailable');const size=Number(response.headers.get('content-length'));if(size>3000000)throw Error('Status payload too large');const body=await response.text();if(body.length>3000000)throw Error('Status payload too large');return JSON.parse(body);}
async function refreshProviderStatus(){const sources={chatgpt:'https://status.openai.com/api/v2/summary.json',claude:'https://status.claude.com/api/v2/summary.json',gemini:'https://www.google.com/appsstatus/dashboard/incidents.json'},prior=GlanceProviderStatus.normalize((await chrome.storage.local.get('providerStatus')).providerStatus),raw={};await Promise.all(Object.entries(sources).map(async([id,url])=>{try{const body=await statusJson(url);raw[id]=id==='gemini'?GlanceProviderStatus.parseGemini(body):GlanceProviderStatus.parseStatuspage(id,body)}catch{raw[id]={...prior[id],state:'unknown',summary:'Status unavailable',checkedAt:Date.now()}}}));const next=GlanceProviderStatus.transition(prior,raw),previousKey=GlanceProviderStatus.incidentKey(prior),nextKey=GlanceProviderStatus.incidentKey(next);await chrome.storage.local.set({providerStatus:next});if(nextKey&&nextKey!==previousKey){const issues=Object.entries(next).filter(([,row])=>row.state==='issue');try{await chrome.notifications.create('llms-provider-status',{type:'basic',iconUrl:'icons/icon128.png',title:'LLMs Monitor · Service alert',message:issues.map(([id,row])=>`${id}: ${row.summary}`).join(' / ').slice(0,400),priority:2})}catch{}const settings={sound:true,volume:18,...(await chrome.storage.local.get('settings')).settings};if(settings.sound!==false)try{if(await ensureOffscreen())await chrome.runtime.sendMessage({type:'PLAY_STATUS_ALERT',volume:settings.volume})}catch{}}return next;}
async function refreshIntelligence(){const saved=await chrome.storage.local.get(['intelligenceFeed','settings']),prior=GlanceIntelligence.normalize(saved.intelligenceFeed);let next;try{const body=await statusJson(GlanceIntelligence.FEED_URL);next=GlanceIntelligence.normalize(body);if(!['ready','unconfigured'].includes(next.status))throw Error('Intelligence unavailable')}catch{next={...prior,status:prior.status==='unconfigured'?'unconfigured':'unavailable',checkedAt:Date.now()}}const fresh=GlanceIntelligence.newAlerts(prior,next);await chrome.storage.local.set({intelligenceFeed:next});if(fresh.length){const row=fresh[0],more=fresh.length>1?` (+${fresh.length-1})`:'';try{await chrome.notifications.create(`llms-intelligence:${row.id}`,{type:'basic',iconUrl:'icons/icon128.png',title:`LLMs Monitor · ${GlanceIntelligence.label(row,'en')}`,message:`${row.account}: ${row.summary}${more}`.slice(0,400),priority:row.severity==='critical'?2:1})}catch{}if(saved.settings?.sound!==false)try{if(await ensureOffscreen())await chrome.runtime.sendMessage({type:'PLAY_STATUS_ALERT',volume:saved.settings?.volume??18})}catch{}}return next;}
async function accept(id,incoming,notify=true){const now=Date.now();let changed=false,wasLogin=false;const snapshot=await updateData(async data=>{const old=data[id]||{};changed=numericChanged(old,incoming);wasLogin=old.status!=='login'&&incoming.status==='login';const next=GlanceState.accept(old,incoming,now);if(changed&&notify){next.changeNotificationPending=true;await (typeof notify==='function'?notify():playChangeSound());delete next.changeNotificationPending}data[id]=next;return next});if(wasLogin)await resetHistoryBaseline(id);if(snapshot.status==='ready')await recordHistory(id,snapshot.windows,now);return {snapshot,changed};}
function timebox(promise,id,ms=25000){let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(`${id} update timeout`)),ms)})]).finally(()=>clearTimeout(timer));}
async function refreshService(id,notifyChange){await updateData(data=>{const snapshot=GlanceState.loading(data[id]);data[id]=snapshot;return snapshot});try{const result=await timebox(FETCHERS[id](),id);delete result.organizationId;return (await accept(id,{...result,source:'api'},notifyChange)).changed;}catch(error){if(error?.login)await accept(id,{status:'login',windows:[],extras:[],plan:'未取得',source:'api',note:'公式サイトでログインしてください。'},false);else await accept(id,{status:'unavailable',source:'api',note:'取得できませんでした。'},false);return false;}}
async function refresh(){const ids=Object.keys(FETCHERS);let soundPromise=null;const notifyChange=()=>soundPromise??=playChangeSound(),results=await Promise.allSettled(ids.map(id=>refreshService(id,notifyChange)));return {ok:true,services:results.map((result,index)=>({service:ids[index],ok:result.status==='fulfilled'}))};}
async function openService(id){if(!URLS[id])throw Error('サービスが見つかりません');await chrome.tabs.create({url:URLS[id],active:true});return {ok:true};}
function floatingTab(win){const target=chrome.runtime.getURL('floating.html');return (win?.tabs||[]).some(tab=>tab.url===target||tab.pendingUrl===target);}
async function openFloating(focus=false){const settings={enabled:true,...(await chrome.storage.local.get('settings')).settings};if(settings.enabled===false)return {ok:false};const saved=await chrome.storage.local.get('floatingWindowId');if(saved.floatingWindowId)try{const win=await chrome.windows.get(saved.floatingWindowId,{populate:true});if(floatingTab(win)){if(focus)await chrome.windows.update(saved.floatingWindowId,{focused:true});return {ok:true};}}catch{}await chrome.storage.local.remove('floatingWindowId');const win=await chrome.windows.create({url:chrome.runtime.getURL('floating.html'),type:'popup',focused:focus});await chrome.storage.local.set({floatingWindowId:win.id});return {ok:true};}
async function closeFloating(){const saved=await chrome.storage.local.get('floatingWindowId');if(saved.floatingWindowId)try{await chrome.windows.remove(saved.floatingWindowId)}catch{}await chrome.storage.local.remove('floatingWindowId');}
async function monitorReady(navigationId,tabId){clearTimeout(monitorCloseTimer);const changed=monitorNavigationId&&monitorNavigationId!==navigationId;monitorNavigationId=String(navigationId||'');monitorTabId=Number.isInteger(tabId)?tabId:monitorTabId;const saved=await chrome.storage.local.get('floatingWindowId');if(changed&&saved.floatingWindowId){const saved=await chrome.storage.local.get('floatingWindowId');if(saved.floatingWindowId)try{const win=await chrome.windows.get(saved.floatingWindowId,{populate:true}),tab=win.tabs?.find(item=>item.url===chrome.runtime.getURL('floating.html'));if(tab?.id)await chrome.tabs.reload(tab.id)}catch{}}return {ok:true};}
function monitorClosed(navigationId){if(String(navigationId||'')!==monitorNavigationId)return {ok:true};clearTimeout(monitorCloseTimer);monitorCloseTimer=setTimeout(()=>{monitorNavigationId='';monitorTabId=null;closeFloating()},1600);return {ok:true};}
async function removeStaleFloating(){const saved=await chrome.storage.local.get('floatingWindowId'),ids=new Set;try{for(const context of await chrome.runtime.getContexts({documentUrls:[chrome.runtime.getURL('floating.html')]})){if(!Number.isInteger(context.tabId))continue;try{const tab=await chrome.tabs.get(context.tabId);if(Number.isInteger(tab.windowId))ids.add(tab.windowId)}catch{}}}catch{}if(saved.floatingWindowId)try{const win=await chrome.windows.get(saved.floatingWindowId,{populate:true});if(floatingTab(win))ids.add(saved.floatingWindowId)}catch{}for(const id of ids)try{await chrome.windows.remove(id)}catch{}await chrome.storage.local.remove('floatingWindowId');}
async function handle(message,sender,external){
 if(!message||typeof message!=='object')throw Error('無効なリクエスト');const origin=(()=>{try{return new URL(sender.url).origin}catch{return ''}})(),trusted=external?ALLOWED.has(origin):sender.url?.startsWith(chrome.runtime.getURL(''));
 if(message.type==='SNAPSHOT'&&!external){const id=message.service;if(!HOSTS[id]||origin!==`https://${HOSTS[id]}`)return {ok:false};const parsedWindows=(Array.isArray(message.windows)?message.windows:[]).filter(item=>item&&typeof item==='object'&&typeof item.remaining==='number'&&Number.isFinite(item.remaining)&&item.remaining>=0&&item.remaining<=100).slice(0,6).map(item=>({label:String(item.label).slice(0,80),remaining:item.remaining,reset:String(item.reset||'').slice(0,150),resetAt:Number.isFinite(Number(item.resetAt))?Number(item.resetAt):null})),windows=id==='chatgpt'?[]:parsedWindows,extras=(Array.isArray(message.extras)?message.extras:[]).slice(0,8).filter(item=>item&&typeof item==='object'&&typeof item.label==='string'&&typeof item.value==='string').map(item=>({label:item.label.slice(0,80),value:item.value.slice(0,160),detail:String(item.detail||'').slice(0,180),expiresAt:Number.isFinite(Number(item.expiresAt))?Number(item.expiresAt):null,observedAt:Number.isFinite(Number(item.observedAt))?Number(item.observedAt):null,barPercent:Number.isFinite(Number(item.barPercent))?Math.max(0,Math.min(100,Number(item.barPercent))):null})),plan=typeof message.plan==='string'?message.plan.slice(0,80):'未取得';await accept(id,{windows,extras,plan,source:'dom',status:message.status==='login'?'login':parsedWindows.length||extras.length||plan!=='未取得'?'ready':'unavailable',note:message.status==='login'?'公式サイトでログインしてください。':'公式画面から取得。'});return {ok:true};}
 if(message.type==='GET'&&(!external||trusted)&&(external||origin===chrome.runtime.getURL('').slice(0,-1)||Object.values(HOSTS).some(host=>origin===`https://${host}`)))return state();if(message.type==='OPEN_CURRENT'&&!external&&HOSTS[message.service]&&origin===`https://${HOSTS[message.service]}`)return openService(message.service);if(!trusted)throw Error('このページからの操作は許可されていません');if(message.type==='MONITOR_READY')return monitorReady(message.navigationId,sender.tab?.id);if(message.type==='MONITOR_CLOSED')return monitorClosed(message.navigationId);if(message.type==='OPEN')return openService(message.service);if(message.type==='REFRESH')return refresh();if(message.type==='FLOAT')return openFloating(true);if(message.type==='CLOSE_FLOAT')return closeFloating();if(message.type==='SETTINGS'){const input=message.settings||{},prior=GlancePreferences.normalize({...DEFAULT_SETTINGS,...(await chrome.storage.local.get('settings')).settings}),settings=GlancePreferences.normalize({opacity:Math.min(100,Math.max(15,Number(input.opacity)||55)),position:['bottom-right','bottom-left','top-right','top-left'].includes(input.position)?input.position:'bottom-right',enabled:input.enabled!==false,theme:input.theme==='standard'?'standard':'dark',language:input.language==='en'?'en':'ja',sound:input.sound!==false,volume:Math.min(50,Math.max(1,Number(input.volume)||18)),serviceOrder:input.serviceOrder??prior.serviceOrder,hiddenServices:input.hiddenServices??prior.hiddenServices});await chrome.storage.local.set({settings});if(!settings.enabled)await closeFloating();return {ok:true};}throw Error('未対応の操作');
}
function listener(external){return(message,sender,reply)=>{if(!external&&['PLAY_CHANGE_SOUND','PLAY_STATUS_ALERT'].includes(message?.type))return false;const task=message?.type==='GET'?handle(message,sender,external):serialize(()=>handle(message,sender,external));task.then(reply,error=>reply({error:error.message}));return true;};}
async function bootstrap(){chrome.alarms.create('llms-refresh',{periodInMinutes:1});chrome.alarms.create('llms-provider-status',{periodInMinutes:1});chrome.alarms.create('llms-intelligence',{periodInMinutes:1});const saved=await chrome.storage.local.get(['settings','historyLast','historyVersion']);const updates={};if(!saved.settings)updates.settings={...DEFAULT_SETTINGS,language:environmentLanguage()};else if(!saved.settings.language||!saved.settings.serviceOrder||!saved.settings.hiddenServices)updates.settings=GlancePreferences.normalize({...DEFAULT_SETTINGS,...saved.settings,language:saved.settings.language||environmentLanguage()});if(!saved.historyLast)updates.historyLast={};if(!Number.isFinite(Number(saved.historyVersion)))updates.historyVersion=0;if(Object.keys(updates).length)await chrome.storage.local.set(updates);await removeStaleFloating();await Promise.allSettled([refresh(),refreshProviderStatus(),refreshIntelligence()]);}
chrome.runtime.onMessage.addListener(listener(false));chrome.runtime.onMessageExternal.addListener(listener(true));chrome.action.onClicked.addListener(()=>chrome.tabs.create({url:chrome.runtime.getURL('index.html')}));chrome.runtime.onInstalled.addListener(()=>serialize(bootstrap));chrome.runtime.onStartup.addListener(()=>serialize(bootstrap));chrome.alarms.onAlarm.addListener(alarm=>{if(alarm.name==='llms-refresh')serialize(refresh);if(alarm.name==='llms-provider-status')serialize(refreshProviderStatus);if(alarm.name==='llms-intelligence')serialize(refreshIntelligence)});chrome.tabs.onRemoved.addListener(tabId=>{if(tabId===monitorTabId)monitorClosed(monitorNavigationId)});chrome.notifications.onClicked.addListener(async id=>{if(id==='llms-provider-status')return chrome.tabs.create({url:chrome.runtime.getURL('index.html')});if(id.startsWith('llms-intelligence:')){const feed=GlanceIntelligence.normalize((await chrome.storage.local.get('intelligenceFeed')).intelligenceFeed),row=feed.alerts.find(item=>item.id===id.slice('llms-intelligence:'.length));if(row?.url)chrome.tabs.create({url:row.url})}});chrome.windows.onRemoved.addListener(async windowId=>{const saved=await chrome.storage.local.get('floatingWindowId');if(saved.floatingWindowId===windowId)await chrome.storage.local.remove('floatingWindowId');});
