(()=>{
const service=location.hostname==='chatgpt.com'?'chatgpt':location.hostname==='claude.ai'?'claude':'gemini';
let lastSignature='',pending=false,lastRead=0,planCache={value:'未取得',at:0};const startedAt=Date.now();
const host=document.createElement('div');host.id='glance-ai-usage-panel';const shadow=host.attachShadow({mode:'closed'});
const style=document.createElement('style');style.textContent=`:host{all:initial!important;position:fixed!important;z-index:2147483646!important;display:block;font:13px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important;color:#eef2fa!important}*{box-sizing:border-box}.panel{max-height:calc(100vh - 32px);overflow-y:auto;width:286px;max-width:calc(100vw - 32px);padding:15px;border:1px solid rgb(255 255 255 / calc(.12 + var(--alpha,.55) * .18));border-radius:14px;background:rgb(9 14 23 / var(--alpha,.55));-webkit-backdrop-filter:blur(2px) saturate(110%);backdrop-filter:blur(2px) saturate(110%);box-shadow:0 10px 35px rgb(0 0 0 / calc(var(--alpha,.55) * .42));line-height:1.5}.widget-title{display:flex;justify-content:space-between;font-weight:600}.widget-title span{font-size:10px;color:#b8c6dd}.widget-row{margin-top:12px;background:transparent}.widget-line{display:flex;justify-content:space-between}.widget-line b{font-weight:500}.widget-line small{font-size:9px;color:#9babc3}.track{height:4px;background:#ffffff20;margin-top:5px;border-radius:3px;overflow:hidden}.track i{display:block;height:100%;background:var(--color)}.widget-meta,.widget-foot{font-size:10px;color:#b5c1d7;margin-top:4px}.widget-foot{margin-top:12px}.actions{display:flex;justify-content:space-between;margin-top:12px}button{border:0;color:#cedbff;background:transparent;cursor:pointer;font:inherit;font-size:11px;padding:3px}button:focus-visible{outline:2px solid #b8c8ff}.collapsed .rows{display:none}.previous,.extra-detail{font-size:10px;color:#adbad0;margin-top:4px;overflow-wrap:anywhere}.extras{border-top:1px solid #ffffff25;margin-top:12px;padding-top:10px}.extras-title{font-size:10px;color:#9fb0ce}.extra-row{margin-top:8px;font-size:10px}.extra-line{display:flex;flex-wrap:wrap;justify-content:space-between;gap:3px 8px}.extra-line b{font-weight:500}.extra-row.urgent,.extra-row.urgent b,.extra-row.urgent .extra-detail,.extra-action{color:#ff737d}.extra-action{text-decoration:underline;text-underline-offset:2px}.panel.light{color:#1d2738;background:rgb(250 251 253 / var(--alpha,.82));border-color:#52647a38;box-shadow:0 10px 35px #29364b30}.panel.light .widget-line small,.panel.light .widget-meta,.panel.light .widget-foot,.panel.light .previous,.panel.light .extra-detail{color:#59677b}.panel.light .extras{border-color:#71809635}.panel.light .extras-title{color:#59677b}.panel.light .track{background:#34465f22}.panel.light button{color:#274e98}.panel.light .extra-row.urgent,.panel.light .extra-row.urgent .extra-detail,.panel.light .extra-action{color:#b01828}.is-updating{animation:glance-pulse 1.6s ease-in-out infinite}@keyframes glance-pulse{0%,100%{opacity:.7}50%{opacity:.35}}@media(prefers-reduced-motion:reduce){.is-updating{animation:none;opacity:.6}}`;
style.textContent+=`.changed-number{color:#ff737d;animation:number-change 1s steps(2,end) infinite}@keyframes number-change{0%,100%{opacity:1}50%{opacity:.32}}@media(prefers-reduced-motion:reduce){.changed-number{animation:none;color:#ff737d}}`;
const panel=document.createElement('div');panel.className='panel';const rows=document.createElement('div');rows.className='rows';const actions=document.createElement('div');actions.className='actions';const open=document.createElement('button');open.textContent='使用量 / ログイン ↗';const collapse=document.createElement('button');collapse.textContent='−';collapse.setAttribute('aria-label','パネルを折りたたむ');actions.append(open,collapse);panel.append(rows,actions);shadow.append(style,panel);document.documentElement.append(host);
open.onclick=()=>chrome.runtime.sendMessage({type:'OPEN_CURRENT',service}).catch(()=>{open.textContent='拡張機能を再接続してください';});collapse.onclick=()=>{panel.classList.toggle('collapsed');collapse.textContent=panel.classList.contains('collapsed')?'+':'−';};
async function draw(){try{const r=await chrome.runtime.sendMessage({type:'GET'});if(!r)return;Glance.observe(r.data||{});rows.innerHTML=Glance.widget(r.data);host.style.setProperty('display',r.settings.enabled?'block':'none','important');const pos=r.settings.position;for(const side of ['top','bottom','left','right'])host.style.setProperty(side,pos.includes(side)?'16px':'auto','important');panel.style.setProperty('--alpha',r.settings.opacity/100);panel.classList.toggle('light',r.settings.theme==='standard')}catch{host.remove();clearInterval(interval)}}
function onUsage(){return service==='chatgpt'?location.pathname==='/settings/usage':service==='gemini'?location.pathname==='/usage':location.hash==='#settings/usage'||location.pathname==='/settings/usage';}
async function chatGPTPlan(){
 if(service!=='chatgpt')return '未取得';if(Date.now()-planCache.at<300000)return planCache.value;
 let value='未取得';for(const path of ['/backend-api/accounts/check/v4-2023-04-27','/backend-api/me']){try{const response=await fetch(path,{credentials:'include',cache:'no-store',headers:{accept:'application/json'}});if(!response.ok)continue;value=GlanceParser.planFromObject(await response.json(),'chatgpt');if(value!=='未取得')break;}catch{}}
 planCache={value,at:Date.now()};return value;
}
async function read(){pending=false;if(Date.now()-lastRead<1500)return;lastRead=Date.now();
 const loginControls=Array.from(document.querySelectorAll('button,a')).filter(e=>e.getClientRects().length).some(e=>/^(ログイン|ログインする|Sign in|Log in)$/i.test((e.textContent||'').trim()));
 const login=/\/(login|auth|signin)(\/|$)/i.test(location.pathname)||loginControls;
 if(!onUsage()&&!login)return;
 const windows=login?[]:GlanceParser.parse(document,service),extras=login||!onUsage()?[]:GlanceParser.parseExtras(document,service);let plan=login?'未取得':GlanceParser.parsePlan(document,service);if(!login&&plan==='未取得')plan=await chatGPTPlan();const status=login?'login':windows.length?'ready':'unavailable';
 if(status==='unavailable'&&Date.now()-startedAt<45000)return;
 const sig=JSON.stringify({windows,extras,plan,status,path:location.href});if(sig===lastSignature)return;lastSignature=sig;
 try{await chrome.runtime.sendMessage({type:'SNAPSHOT',service,windows,extras,plan,status})}catch{}
}
const observer=new MutationObserver(()=>{if(!pending){pending=true;setTimeout(read,1800)}});observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-valuenow','aria-valuetext']});
window.addEventListener('hashchange',()=>{lastSignature='';read()});const interval=setInterval(()=>{draw();read()},2000);draw();setTimeout(read,2500);
})();
