(()=>{
const service=location.hostname==='chatgpt.com'?'chatgpt':location.hostname==='claude.ai'?'claude':'gemini';
let lastSignature='',pending=false,lastRead=0,statusOpen=false,feedOpen=false,lastAlertKey='',lastProviderStatus={},planCache={value:'未取得',at:0};const startedAt=Date.now();
const host=document.createElement('div');host.id='glance-ai-usage-panel';const shadow=host.attachShadow({mode:'closed'});
const style=document.createElement('style');style.textContent=`:host{all:initial!important;position:fixed!important;z-index:2147483646!important;display:block;font:13px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important;color:#eef2fa!important}*{box-sizing:border-box}.panel{max-height:calc(100vh - 32px);overflow-y:auto;width:286px;max-width:calc(100vw - 32px);padding:15px;border:1px solid rgb(255 255 255 / calc(.12 + var(--alpha,.55) * .18));border-radius:14px;background:rgb(9 14 23 / var(--alpha,.55));-webkit-backdrop-filter:blur(2px) saturate(110%);backdrop-filter:blur(2px) saturate(110%);box-shadow:0 10px 35px rgb(0 0 0 / calc(var(--alpha,.55) * .42));line-height:1.5}.widget-title{display:flex;justify-content:space-between;font-weight:600}.widget-title span{font-size:10px;color:#b8c6dd}.widget-row{margin-top:12px;background:transparent}.widget-line{display:flex;justify-content:space-between}.widget-line b{font-weight:500}.widget-line small{font-size:9px;color:#9babc3}.track{--panel-track:#ffffff20;height:4px;background:#ffffff20;margin-top:5px;border-radius:3px;overflow:hidden}.track i{display:block;height:100%;background:var(--color)}.widget-meta,.widget-foot{font-size:10px;color:#b5c1d7;margin-top:4px}.widget-foot{margin-top:12px}.actions{display:flex;justify-content:space-between;margin-top:12px}button{border:0;color:#cedbff;background:transparent;cursor:pointer;font:inherit;font-size:11px;padding:3px}button:focus-visible{outline:2px solid #b8c8ff}.collapsed .rows{display:none}.previous,.extra-detail{font-size:10px;color:#adbad0;margin-top:4px;overflow-wrap:anywhere}.extras{border-top:1px solid #ffffff25;margin-top:12px;padding-top:10px}.extras-title{font-size:10px;color:#9fb0ce}.extra-row{margin-top:8px;font-size:10px}.extra-line{display:flex;flex-wrap:wrap;justify-content:space-between;gap:3px 8px}.extra-line b{font-weight:500}.extra-row.urgent,.extra-row.urgent b,.extra-row.urgent .extra-detail,.extra-action{color:#ff737d}.extra-action{text-decoration:underline;text-underline-offset:2px}.panel.light{color:#1d2738;background:rgb(250 251 253 / var(--alpha,.82));border-color:#52647a38;box-shadow:0 10px 35px #29364b30}.panel.light .widget-line small,.panel.light .widget-meta,.panel.light .widget-foot,.panel.light .previous,.panel.light .extra-detail{color:#59677b}.panel.light .extras{border-color:#71809635}.panel.light .extras-title{color:#59677b}.panel.light .track{background:#34465f22;--panel-track:#34465f22}.panel.light button{color:#274e98}.panel.light .extra-row.urgent,.panel.light .extra-row.urgent .extra-detail,.panel.light .extra-action{color:#b01828}.is-updating{animation:glance-pulse 1.6s ease-in-out infinite}@keyframes glance-pulse{0%,100%{opacity:.7}50%{opacity:.35}}@media(prefers-reduced-motion:reduce){.is-updating{animation:none;opacity:.6}}`;
style.textContent+=`.changed-number{color:#ff737d;animation:number-change 1s steps(2,end) infinite}@keyframes number-change{0%,100%{opacity:1}50%{opacity:.32}}@media(prefers-reduced-motion:reduce){.changed-number{animation:none;color:#ff737d}}`;
style.textContent+=`.deadline-near,.deadline-critical{display:inline-block;padding:2px 4px;border-radius:4px;background:#b51d2f!important;color:#fff!important}.deadline-critical{animation:deadline-breathe 2s ease-in-out infinite}@keyframes deadline-breathe{50%{opacity:.48}}.extra-row.deadline-near,.extra-row.deadline-critical{padding:5px}.extra-row.deadline-near *,.extra-row.deadline-critical *{color:#fff!important}.weekly-track{position:relative}.weekly-track:after{content:"";position:absolute;inset:0;background:repeating-linear-gradient(90deg,transparent 0 calc(var(--segment-size) - 1px),var(--panel-track,#ffffff20) calc(var(--segment-size) - 2px) var(--segment-size));pointer-events:none}.session-equivalent{font-size:9px;color:#aebbd0;margin-top:3px}.panel.light .session-equivalent{color:#59677b}@media(prefers-reduced-motion:reduce){.deadline-critical{animation:none}}`;
style.textContent+=`.widget-reset.deadline-near,.widget-reset.deadline-critical{display:block;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;color:inherit!important}.widget-reset .time-urgent.deadline-near,.widget-reset .time-urgent.deadline-critical{display:inline-block;padding:2px 5px!important;border:1px solid #d58b95!important;border-radius:6px!important;background:#8b394730!important;color:#ffc7cf!important;box-shadow:inset 3px 0 0 #d67b88!important}.panel.light .widget-reset .time-urgent.deadline-near,.panel.light .widget-reset .time-urgent.deadline-critical{background:#fff0f1!important;color:#913344!important}.provider-status{margin:7px 0;border:1px solid #ffffff35;border-radius:8px;padding:5px 7px;font-size:10px}.provider-status.has-issue{border-color:#ff727d;background:#601923aa}.provider-status summary{cursor:pointer;font-weight:700}.provider-status-list{margin-top:6px}.provider-status-row{display:grid;gap:2px;border-top:1px solid #ffffff24;padding:5px 0}.provider-status-row.issue{color:#ff9da5}.provider-status-row a{color:#a9c6ff;text-decoration:underline}.provider-status small{display:block;color:#bbc9da}.panel.light .provider-status{border-color:#54657960}.panel.light .provider-status.has-issue{background:#ffe4e7}.panel.light .provider-status-row a{color:#2859aa}.panel.light .provider-status small{color:#526278}`;
style.textContent+=`.deadline-near,.deadline-critical{border:1px solid #d58b95!important;border-radius:6px!important;background:#8b394730!important;color:#ffc7cf!important;box-shadow:inset 3px 0 0 #d67b88!important}.deadline-critical{background:#a7374938!important;color:#ffe5e8!important}.extra-row.deadline-near *,.extra-row.deadline-critical *{color:inherit!important}.panel.light .deadline-near,.panel.light .deadline-critical{background:#fff0f1!important;color:#913344!important}.provider-status.has-recovery{background:#164135a8;border-color:#56ae8a;color:#c8f3df}.provider-status-row.recovered{color:#89dfb6}.panel.light .provider-status.has-recovery{background:#e7f7ef;color:#196344}.panel.light .provider-status-row.recovered{color:#196344}.provider-status-popover>small{display:block;margin-top:5px;color:#bbc9da}`;
style.textContent+=`.entitlement-line{display:flex;justify-content:space-between;align-items:center;gap:7px}.entitlement-official{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:9px;letter-spacing:-.03em;margin-top:3px;color:#b9c6d9}.panel.light .entitlement-official{color:#526278}`;
style.textContent+=`.api-credit-row{margin-top:8px;padding-top:7px;border-top:1px dashed #8293ae40;font-size:10px}.api-credit-row a{color:inherit;text-decoration:underline}.api-credit-row small{display:block;font-size:9px;color:#a5b2c8}.api-credit-row a small{display:inline}.api-credit-stale{opacity:.65}.panel.light .api-credit-row small{color:#59677b}`;
const panel=document.createElement('div');panel.className='panel';const rows=document.createElement('div');rows.className='rows';const actions=document.createElement('div');actions.className='actions';const open=document.createElement('button');const collapse=document.createElement('button');collapse.textContent='−';actions.append(open,collapse);panel.append(rows,actions);shadow.append(style,panel);document.documentElement.append(host);
open.onclick=()=>chrome.runtime.sendMessage({type:'OPEN_CURRENT',service}).catch(()=>{open.textContent=GlanceLocale.language()==='ja'?'拡張機能を再接続してください':'Reconnect the extension';});rows.addEventListener('click',event=>{if(event.target.closest('.provider-status > summary'))statusOpen=!statusOpen;if(event.target.closest('.intelligence-feed > summary'))feedOpen=!feedOpen});collapse.onclick=()=>{panel.classList.toggle('collapsed');collapse.textContent=panel.classList.contains('collapsed')?'+':'−';};
async function draw(){try{const r=await chrome.runtime.sendMessage({type:'GET'});if(!r)return;GlanceLocale.setLanguage(r.settings?.language==='en'?'en':'ja');open.textContent=GlanceLocale.language()==='ja'?'使用量 / ログイン ↗':'Usage / Sign in ↗';collapse.setAttribute('aria-label',GlanceLocale.language()==='ja'?'パネルを折りたたむ':'Collapse panel');GlanceApiCredits.set(r.apiCredits);Glance.observe(r.data||{});const previouslyRecovered=Object.values(GlanceProviderStatus.normalize(lastProviderStatus)).some(row=>row.state==='recovered');lastProviderStatus=r.providerStatus;const key=GlanceProviderStatus.incidentKey(r.providerStatus);if(key&&key!==lastAlertKey)statusOpen=true;if(!previouslyRecovered&&Object.values(GlanceProviderStatus.normalize(r.providerStatus)).some(row=>row.state==='recovered'))statusOpen=true;lastAlertKey=key;const openHistory=new Set([...rows.querySelectorAll('.widget-history[open]')].map(node=>node.dataset.historyId));rows.innerHTML=Glance.widget(r.data,r.settings,r.providerStatus,statusOpen,r.intelligenceFeed,feedOpen);for(const node of rows.querySelectorAll('.widget-history'))node.open=openHistory.has(node.dataset.historyId);Glance.decorate(rows,r.data,r.settings);host.style.setProperty('display',r.settings.enabled&&GlancePreferences.visible(r.settings).includes(service)?'block':'none','important');const pos=r.settings.position;for(const side of ['top','bottom','left','right'])host.style.setProperty(side,pos.includes(side)?'16px':'auto','important');panel.style.setProperty('--alpha',r.settings.opacity/100);panel.classList.toggle('light',r.settings.theme==='standard')}catch{host.remove();clearInterval(interval)}}
function onUsage(){return service==='chatgpt'?location.pathname==='/settings/usage':service==='gemini'?location.pathname==='/usage':location.hash==='#settings/usage'||location.pathname==='/settings/usage';}
async function chatGPTPlan(){
 if(service!=='chatgpt')return '未取得';if(Date.now()-planCache.at<300000)return planCache.value;
 let value='未取得';for(const path of ['/backend-api/accounts/check/v4-2023-04-27','/backend-api/me']){try{const response=await fetch(path,{credentials:'include',cache:'no-store',headers:{accept:'application/json'}});if(!response.ok)continue;value=GlanceParser.planFromObject(await response.json(),'chatgpt');if(value!=='未取得')break;}catch{}}
 planCache={value,at:Date.now()};return value;
}
async function read(){pending=false;if(Date.now()-lastRead<1500)return;lastRead=Date.now();
 const loginControls=Array.from(document.querySelectorAll('button,a')).filter(e=>e.getClientRects().length).some(e=>/^(ログイン|ログインする|Sign in|Log in)$/i.test((e.textContent||'').trim()));
 const login=/\/(login|auth|signin)(\/|$)/i.test(location.pathname)||loginControls;
 const usagePage=onUsage();if(!usagePage&&!login&&service!=='gemini')return;
 const windows=login||!usagePage?[]:GlanceParser.parse(document,service),extras=login||!usagePage?[]:GlanceParser.parseExtras(document,service);let plan=login?'未取得':GlanceParser.parsePlan(document,service);if(!login&&plan==='未取得')plan=await chatGPTPlan();if(service==='gemini'&&!usagePage&&plan==='未取得')return;const status=login?'login':windows.length||extras.length||plan!=='未取得'?'ready':'unavailable';
 if(status==='unavailable'&&Date.now()-startedAt<45000)return;
 const sig=JSON.stringify({windows,extras,plan,status,path:location.href});if(sig===lastSignature)return;lastSignature=sig;
 try{await chrome.runtime.sendMessage({type:'SNAPSHOT',service,windows,extras,plan,status})}catch{}
}
chrome.runtime.onMessage.addListener((message,_,reply)=>{if(message?.type==='GLANCE_USAGE_READER_PING'){reply({ready:true,usagePage:onUsage()});return false}if(message?.type==='GLANCE_USAGE_READER_READ'){lastRead=0;lastSignature='';read().then(()=>reply({ready:true}),()=>reply({ready:false}));return true}return false});
const observer=new MutationObserver(()=>{if(!pending){pending=true;setTimeout(read,1800)}});observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-valuenow','aria-valuetext']});
window.addEventListener('hashchange',()=>{lastSignature='';read()});const interval=setInterval(()=>{draw();read()},2000);draw();setTimeout(read,2500);
})();
