(function(root){
 const clamp=n=>Math.max(0,Math.min(100,Math.round(Number(n))));
 const text=v=>String(v??'').trim();
 function plan(value,service){
  const raw=text(value).replace(/[_-]+/g,' ').replace(/^chatgpt\s+/i,'').trim().toLowerCase();
  if(service==='chatgpt'){const names={free:'Free',go:'Go',plus:'Plus',pro:'Pro',business:'Business',team:'Team',enterprise:'Enterprise',edu:'Edu'};return names[raw]||'未取得';}
  if(service==='claude'){if(/max.*20/.test(raw))return 'Max 20x';if(/max.*5/.test(raw))return 'Max 5x';if(raw.includes('max'))return 'Max';if(raw.includes('pro'))return 'Pro';if(raw.includes('team'))return 'Team';if(raw.includes('enterprise'))return 'Enterprise';if(raw.includes('free'))return 'Free';return '未取得';}
  if(/ultra/.test(raw))return 'Google AI Ultra';if(/pro/.test(raw))return 'Google AI Pro';if(/plus/.test(raw))return 'Google AI Plus';if(/free/.test(raw))return 'Free';return '未取得';
 }
 function jsonScript(html,id){const escaped=id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),match=String(html).match(new RegExp(`<script[^>]*id=["']${escaped}["'][^>]*>([\\s\\S]*?)<\\/script>`,'i'));if(!match)return null;try{return JSON.parse(match[1])}catch{return null}}
 function deep(object,path){return path.reduce((value,key)=>value?.[key],object)}
 function chatGPTBootstrap(html){const data=jsonScript(html,'client-bootstrap')||{},account=deep(data,['session','account'])||{},custom=deep(data,['statsigPayload','user','custom'])||{};return {accessToken:deep(data,['session','accessToken'])||'',accountId:account.id||account.accountId||'',plan:plan(account.planType||custom.plan_type,'chatgpt')};}
 function resetTime(value){if(!value)return null;const number=Number(value),date=Number.isFinite(number)?new Date(number>1e12?number:number*1000):new Date(value);return Number.isNaN(date.getTime())?null:date.getTime();}
 function resetLabel(value){const time=resetTime(value);if(!time)return '';return `リセット ${new Date(time).toLocaleString('ja-JP',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}`;}
 function chatWindow(raw,fallback,now){if(!raw||typeof raw!=='object')return null;const used=raw.used_percent??raw.usedPercent;if(!Number.isFinite(Number(used)))return null;const seconds=Number(raw.limit_window_seconds??raw.limitWindowSeconds),label=seconds>=600000?'Work / Codex · 週間':seconds>=14000?'Work / Codex · 5時間':fallback,reset=raw.reset_at??raw.resetAt??(raw.reset_after_seconds?now/1000+Number(raw.reset_after_seconds):null);return {label,remaining:clamp(100-Number(used)),reset:resetLabel(reset),resetAt:resetTime(reset)};}
 function parseChatGPTUsage(payload,meta={},now=Date.now()){const rate=payload?.rate_limit||payload?.rateLimit||payload||{},windows=[chatWindow(rate.primary_window||rate.primaryWindow,'Work / Codex · 5時間',now),chatWindow(rate.secondary_window||rate.secondaryWindow,'Work / Codex · 週間',now)].filter(Boolean).sort((a,b)=>a.label.includes('5時間')?-1:b.label.includes('5時間')?1:0),credits=payload?.credits||rate.credits||{},extras=[];if(credits.unlimited===true)extras.push({label:'クレジット',value:'無制限',detail:''});else if(credits.balance!=null)extras.push({label:'クレジット',value:`残り ${credits.balance}`,detail:credits.has_credits===false?'追加クレジットなし':''});return {status:windows.length?'ready':'unavailable',windows,extras,plan:meta.plan!=='未取得'?meta.plan:plan(payload?.plan_type||payload?.planType,'chatgpt'),note:'公式セッションからバックグラウンド取得。'};}
 async function fetchChatGPT(fetcher=fetch){const page=await fetcher('https://chatgpt.com/settings/usage?tab=overview',{credentials:'include',cache:'no-store'});if(!page.ok)throw Object.assign(Error('ChatGPT usage page'),{login:page.status===401||page.status===403});const meta=chatGPTBootstrap(await page.text());if(!meta.accessToken)throw Object.assign(Error('ChatGPT login required'),{login:true});let payload;try{const response=await fetcher('https://chatgpt.com/backend-api/wham/usage?supports_rewardless_invites=true',{credentials:'include',cache:'no-store',headers:{accept:'application/json',authorization:`Bearer ${meta.accessToken}`,...(meta.accountId?{'ChatGPT-Account-Id':meta.accountId}:{})}});if(!response.ok)throw Object.assign(Error('ChatGPT usage API'),{login:response.status===401||response.status===403});payload=await response.json();}finally{meta.accessToken='';meta.accountId='';}return parseChatGPTUsage(payload,meta);}
 function utilization(value){const n=Number(value);if(!Number.isFinite(n))return null;return n<=1?clamp(100-n*100):clamp(100-n);}
 function nestedPlan(object,service,depth=0){if(!object||typeof object!=='object'||depth>5)return '未取得';for(const[key,value]of Object.entries(object)){if(/plan|tier|subscription|billing|entitlement|product/i.test(key)&&typeof value==='string'){const found=plan(value,service);if(found!=='未取得')return found;}if(value&&typeof value==='object'){const found=nestedPlan(value,service,depth+1);if(found!=='未取得')return found;}}return '未取得';}
 function parseClaude(org,usage={},credits={}){const definitions=[['five_hour','現在のセッション'],['seven_day','週間'],['seven_day_sonnet','Sonnet · 週間'],['seven_day_opus','Opus · 週間'],['seven_day_oauth_apps','OAuthアプリ · 週間'],['seven_day_cowork','Cowork · 週間']],windows=[];for(const[key,label]of definitions){const item=usage[key];if(!item)continue;const remaining=utilization(item.utilization);if(remaining!==null)windows.push({label,remaining,reset:resetLabel(item.resets_at),resetAt:resetTime(item.resets_at)});}const extras=[];const balance=credits.balance??credits.amount??credits.remaining_balance;if(balance!=null)extras.push({label:'使用クレジット',value:`残り ${balance}`,detail:credits.currency||''});const extra=usage.extra_usage;if(extra&&typeof extra==='object'){if(extra.monthly_limit!=null)extras.push({label:'クラウドセッションクレジット',value:String(extra.monthly_limit),detail:extra.used_credits!=null?`使用 ${extra.used_credits}`:''});if(extra.used_credits!=null)extras.push({label:'プロジェクトセットアップクレジット',value:String(extra.used_credits),detail:''});}return {status:windows.length?'ready':'unavailable',windows,extras,plan:nestedPlan(org,'claude'),note:org?.name?`${org.name} · 公式セッションから取得。`:'公式セッションからバックグラウンド取得。',organizationId:org?.uuid||org?.id||''};}
 async function fetchClaude(fetcher=fetch,preferredId=''){const organizations=await fetcher('https://claude.ai/api/organizations',{credentials:'include',cache:'no-store'});if(!organizations.ok)throw Object.assign(Error('Claude organizations'),{login:organizations.status===401||organizations.status===403});const list=await organizations.json(),items=Array.isArray(list)?list:list.organizations||[];if(!items.length)throw Object.assign(Error('Claude login required'),{login:true});const org=items.find(item=>(item.uuid||item.id)===preferredId)||items.find(item=>item.is_active)||items[0],id=org.uuid||org.id;const [usageResult,creditResult]=await Promise.all([fetcher(`https://claude.ai/api/organizations/${encodeURIComponent(id)}/usage`,{credentials:'include',cache:'no-store'}),fetcher(`https://claude.ai/api/organizations/${encodeURIComponent(id)}/prepaid/credits`,{credentials:'include',cache:'no-store'})]);if(!usageResult.ok)throw Object.assign(Error('Claude usage API'),{login:usageResult.status===401||usageResult.status===403});return parseClaude(org,await usageResult.json(),creditResult.ok?await creditResult.json():{});}
 function token(source,key){const match=String(source).match(new RegExp(`["']?${key}["']?\\s*:\\s*["']([^"']+)["']`));return match?.[1]||'';}
 function geminiPlan(html){const source=String(html).replace(/\\u0022/gi,'"').replace(/\\"/g,'"'),match=source.match(/tier-pill[^>]*>\s*(?:<[^>]+>\s*)*([^<\r\n]+)/i)||source.match(/["']?(?:tierName|tier_name|planName|plan_name|subscriptionTier)["']?\s*[:=]\s*["']([^"']+)/i)||source.match(/(?:Google AI|AI)\s+(Ultra|Pro|Plus)/i);return plan(match?.[1]||match?.[0],'gemini');}
 function findRpc(value,out=[]){if(!Array.isArray(value))return out;if(value[0]==='wrb.fr'&&value[1]==='jSf9Qc')out.push(value[2]);for(const item of value)if(Array.isArray(item))findRpc(item,out);return out;}
 function parseGeminiBatch(raw){const payloads=[];for(const line of String(raw).replace(/^\)\]\}'[^\n]*\n/,'').split(/\n/)){const value=line.trim();if(!value.startsWith('['))continue;try{findRpc(JSON.parse(value),payloads)}catch{}}let rows=[];for(const payload of payloads)try{const parsed=typeof payload==='string'?JSON.parse(payload):payload;if(Array.isArray(parsed?.[1])){rows=parsed[1];break;}}catch{}const windows=[];for(const row of rows){if(!Array.isArray(row)||!Number.isFinite(Number(row[1])))continue;const kind=Number(row[2]),remaining=clamp((1-Number(row[1]))*100),stamp=row?.[3]?.[0],seconds=Array.isArray(stamp)?Number(stamp[0])+Number(stamp[1]||0)/1e6:Number(stamp);windows.push({label:kind===2?'週間':'現在のセッション',remaining,reset:resetLabel(seconds),resetAt:resetTime(seconds)});}return windows.sort((a,b)=>a.label==='現在のセッション'?-1:b.label==='現在のセッション'?1:0);}
 async function fetchGemini(fetcher=fetch){for(const prefix of ['','/u/0','/u/1']){const page=await fetcher(`https://gemini.google.com${prefix}/usage?pageId=none&t=${Date.now()}`,{credentials:'include',cache:'no-store'});if(!page.ok)continue;const html=await page.text();if(/accounts\.google\.com|Sign in to continue/i.test(page.url||'')||/Sign in to continue/i.test(html))continue;const bl=token(html,'cfb2h'),sid=token(html,'FdrFJe'),at=token(html,'SNlM0e'),locale=token(html,'GGcqce')||'ja';if(!bl||!sid||!at)continue;const query=new URLSearchParams({rpcids:'jSf9Qc','source-path':`${prefix}/usage`,bl,'f.sid':sid,hl:locale,_reqid:String(Math.floor(Math.random()*900000)+100000),rt:'c'}),body=new URLSearchParams({'f.req':JSON.stringify([[['jSf9Qc','[]',null,'generic']]]),at}),result=await fetcher(`https://gemini.google.com${prefix}/_/BardChatUi/data/batchexecute?${query}`,{method:'POST',credentials:'include',cache:'no-store',headers:{'content-type':'application/x-www-form-urlencoded;charset=UTF-8','x-same-domain':'1'},body});if(!result.ok)continue;const windows=parseGeminiBatch(await result.text());if(windows.length)return {status:'ready',windows,extras:[],plan:geminiPlan(html),note:'公式セッションからバックグラウンド取得。'};}throw Object.assign(Error('Gemini login required or usage unavailable'),{login:true});}
 root.GlanceFetchers={plan,chatGPTBootstrap,parseChatGPTUsage,parseClaude,geminiPlan,parseGeminiBatch,fetchChatGPT,fetchClaude,fetchGemini};if(typeof module!=='undefined')module.exports=root.GlanceFetchers;
})(globalThis);
