(function(root){
 const APP_VERSION='1.5.1',HISTORY_LIMIT=10000;
 const services={chatgpt:{name:'ChatGPT',color:'#6dd8bf',mark:'◎',url:'https://chatgpt.com/settings/usage?tab=overview'},claude:{name:'Claude',color:'#eda681',mark:'✳',url:'https://claude.ai/new#settings/usage'},gemini:{name:'Gemini',color:'#93b3ff',mark:'✦',url:'https://gemini.google.com/usage'}};
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function fresh(s){return !!s?.capturedAt && Date.now()-s.capturedAt<125000;}
 function percent(v){return typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=100?v:null;}
 function value(v){return percent(v)===null?'—':`${Math.round(v)}%`;}
 function label(v){return v==='Work / Codex · 週間'?'週間 (Work / Codex)':String(v??'');}
 function updating(s){return !!s?.refreshing&&Date.now()-(s.refreshStartedAt||0)<45000;}
 function status(s){if(!s)return '未接続';if(s.status==='login')return 'ログインが必要';if(updating(s))return '更新中';if(s.status==='loading'||s.status==='error')return '更新待ち（前回値）';if(!fresh(s))return '更新待ち';return s.windows?.length?'取得済み':'数値未取得';}
 function date(t){return t?new Date(t).toLocaleString('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}):'日時未取得';}
 function resetUrgent(w){const ms=Number(w?.resetAt)-Date.now();return Number.isFinite(ms)&&ms>0&&ms<7200000;}
 function resetInside(w){if(!w?.resetAt)return escape(w?.reset||'リセット時刻未取得');const ms=w.resetAt-Date.now(),minutes=Math.max(0,Math.ceil(ms/60000)),left=ms<=0?'まもなくリセット':minutes<60?`あと${minutes}分`:`あと${Math.floor(minutes/60)}時間${minutes%60}分`;return `${escape(w.reset)}<strong class="${resetUrgent(w)?'time-urgent':''}">${resetUrgent(w)?'<span aria-hidden="true">⚠︎ </span>':''}${escape(left)}</strong>`;}
 function historyDate(t){if(!t)return '日時未取得';const d=new Date(t),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`;}
 function previous(w){return w?.previous?`<div class="previous">前回 ${escape(w.previous.value??value(w.previous.remaining))} · ${escape(date(w.previous.capturedAt))}</div>`:'';}
 const changes=GlanceChanges.createTracker();
 function observe(data){for(const [id,s]of Object.entries(data)){if(s.status==='login'){changes.clear(id);continue}if(s.status!=='ready'||s.refreshing)continue;for(const w of s.windows||[])changes.observe(id,'window:'+w.label,value(w.remaining));for(const e of s.extras||[])changes.observe(id,'extra:'+e.label,e.value);}}
 function numeric(id,key,text){let i=0;return String(text??'').split(/(\d+(?:,\d{3})*(?:\.\d+)?)/g).map((part,index)=>{if(index%2===0)return escape(part);const end=changes.deadline(id,key,i++);return end?`<span class="changed-number" style="animation-delay:-${(Date.now()%1000)/1000}s">${escape(part)}</span>`:escape(part)}).join('');}
 function extras(data,id){const s=data[id],items=s?.extras||[];const entries=items.map(e=>{const urgent=!!e.expiresAt&&e.expiresAt-Date.now()<=7*86400000,bar=typeof e.barPercent==='number'?`<div class="track extra-track" aria-label="${escape(e.label+' 残り '+value(e.barPercent))}"><i style="width:${percent(e.barPercent)??0}%"></i></div>`:'',resetAvailable=id==='chatgpt'&&e.label==='利用上限のリセット'&&/利用可能\s*[1-9]\d*/.test(e.value),count=e.value.match(/\d+/)?.[0],shown=resetAvailable?`<a class="extra-action" href="${services.chatgpt.url}" target="_blank" rel="noopener" title="ChatGPTでリセットを利用"><span aria-hidden="true">🎟</span> [利用可能]</a>${count?` ×${escape(count)}`:''}`:numeric(id,'extra:'+e.label,e.value),warning=urgent?'<span class="expiry-warning" title="期限まで1週間以内" aria-label="期限まで1週間以内">⚠︎</span> ':'';return `<div class="extra-row${urgent?' urgent':''}"><div class="extra-line"><span>${escape(e.label)}</span><b>${shown}</b></div>${bar}${e.detail?`<div class="extra-detail">${warning}${escape(e.detail)}</div>`:''}${previous(e)}</div>`});return '<div class="extras"><div class="extras-title">補足情報</div>'+(entries.length?entries.join(''):'<div class="extra-detail">追加クレジット情報は未取得</div>')+(s?.capturedAt?`<div class="extra-detail">取得日時 ${escape(date(s.capturedAt))}</div>`:'')+'</div>';}
 function age(s){if(!s?.capturedAt)return '未取得';const n=Math.max(0,Math.floor((Date.now()-s.capturedAt)/1000));return n<60?`${n}秒前に取得`:`${Math.floor(n/60)}分前に取得`;}
 function historyRows(s,labelValue){const aliases=labelValue==='週間 (Work / Codex)'?['週間 (Work / Codex)','Work / Codex · 週間']:labelValue==='Work / Codex · 週間'?['Work / Codex · 週間','週間 (Work / Codex)']:[labelValue];return aliases.flatMap(key=>s?.history?.[key]||[]).sort((a,b)=>a.capturedAt-b.capturedAt).filter((r,i,rows)=>i===0||r.remaining!==rows[i-1]?.remaining).slice(-HISTORY_LIMIT);}
 function historyBox(s){const labels=[...(s?.windows||[]).map(w=>w.label),...Object.keys(s?.history||{})].filter((name,index,all)=>all.indexOf(name)===index),groups=labels.map(name=>{const rows=historyRows(s,name).reverse(),shown=label(name),lines=rows.map(r=>`${historyDate(r.capturedAt)}　残り使用量 ${value(r.remaining)}`).join('\n');return `<section class="history-group"><div class="history-label">${escape(shown)} <span>${rows.length.toLocaleString('ja-JP')}件</span></div>${rows.length?`<textarea class="history-log" readonly wrap="off" aria-label="${escape(shown)}の変化履歴">${escape(lines)}</textarea>`:'<div class="history-empty">数値が変化すると記録されます</div>'}</section>`}).join('');return `<div class="history"><div class="extras-title">変化履歴</div>${groups||'<div class="history-empty">利用枠の履歴はありません</div>'}</div>`;}
 function widget(data={}){return `<div class="widget-title">LLMs トークン残量モニタ <span>v${APP_VERSION}</span></div>`+Object.entries(services).map(([id,p])=>{const s=data[id],w=s?.windows?.[0],v=percent(w?.remaining);return `<div class="widget-row" style="--color:${p.color}" aria-busy="${updating(s)}"><div class="widget-line"><span>${p.name} <small>${escape(s?.plan||'未取得')}</small></span><b>${numeric(id,'window:'+w?.label,value(v))}</b></div><div class="track"><i style="width:${v??0}%"></i></div><div class="widget-meta">${escape(label(w?.label)||'未取得')} · ${escape(status(s))}${id==='chatgpt'?' / Chat対象外':''}</div>${(s?.windows||[]).slice(1).map(x=>`<div class="widget-meta">${escape(label(x.label))} · 残り ${numeric(id,'window:'+x.label,value(x.remaining))}</div>`).join('')}${extras(data,id)}</div>`}).join('')+`<div class="widget-foot">公式画面を60秒ごとに確認<br><small>LLMs TOKEN USAGE MONITOR v${APP_VERSION}<br>Copyright (C) 2026 NT MicroSystems,Inc.</small></div>`;}
 root.Glance={APP_VERSION,HISTORY_LIMIT,services,escape,fresh,percent,value,label,status,age,widget,previous,extras,historyBox,historyDate,resetInside,resetUrgent,updating,observe,numeric,changes};
})(globalThis);
