(function(root){
 const APP_VERSION='1.5.3',HISTORY_LIMIT=10000,L=root.GlanceLocale||{language:()=> 'ja',t:key=>key,label:value=>String(value??''),locale:()=> 'ja-JP'};
 const services={chatgpt:{name:'ChatGPT',color:'#6dd8bf',mark:'◎',url:'https://chatgpt.com/settings/usage?tab=overview'},claude:{name:'Claude',color:'#eda681',mark:'✳',url:'https://claude.ai/new#settings/usage'},gemini:{name:'Gemini',color:'#93b3ff',mark:'✦',url:'https://gemini.google.com/usage'}};
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function fresh(s){return !!s?.capturedAt && Date.now()-s.capturedAt<125000;}
 function percent(v){return typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=100?v:null;}
 function value(v){return percent(v)===null?'—':`${Math.round(v)}%`;}
 function label(v){return L.label(v);}
 function updating(s){return !!s?.refreshing&&Date.now()-(s.refreshStartedAt||0)<45000;}
 function status(s){if(!s)return L.t('notConnected');if(s.status==='login')return L.t('loginRequired');if(updating(s))return L.t('updating');if(s.status==='loading'||s.status==='error')return L.t('waitingPrevious');if(!fresh(s))return L.t('waiting');return s.windows?.length?L.t('acquired'):L.t('valueMissing');}
 function date(t){return t?new Date(t).toLocaleString(L.locale(),{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}):L.t('dateMissing');}
 function resetUrgent(w){const ms=Number(w?.resetAt)-Date.now();return Number.isFinite(ms)&&ms>0&&ms<7200000;}
 function displayText(value){if(L.language()==='ja')return String(value??'');return String(value??'').replaceAll('更新中 · 前回取得値を表示しています。','Refreshing · Showing the last retrieved values.').replaceAll('取得できませんでした · 前回取得値を表示しています。','Could not refresh · Showing the last retrieved values.').replaceAll('公式セッションからバックグラウンド取得。','Retrieved from the official session.').replaceAll('公式画面から取得。','Retrieved from the official page.').replaceAll('公式サイトでログインしてください。','Please sign in on the official website.').replaceAll('取得できませんでした。','Could not retrieve data.').replaceAll('最初のメッセージから開始します','Starts with the first message').replaceAll('リセット時刻未取得','Reset time unavailable').replaceAll('リセット ','Reset ').replaceAll('無制限','Unlimited').replaceAll('追加クレジットなし','No additional credits').replaceAll('残量未取得','Balance unavailable').replaceAll('有無を取得できません','Availability unavailable').replaceAll('利用可能','Available').replaceAll('期限切れ','Expired').replaceAll('24時間以内','Within 24 hours').replaceAll('完全リセット（週間＋5時間）','Full reset (weekly + 5 hours)').replaceAll('週間リセット','Weekly reset').replaceAll('5時間リセット','5-hour reset');}
 function resetInside(w){if(!w?.resetAt)return escape(displayText(w?.reset||L.t('resetMissing')));const ms=w.resetAt-Date.now(),minutes=Math.max(0,Math.ceil(ms/60000)),left=ms<=0?L.t('resetSoon'):minutes<60?L.t('minutesLeft',{n:minutes}):L.t('hoursLeft',{h:Math.floor(minutes/60),m:minutes%60});return `${escape(displayText(w.reset))}<strong class="${resetUrgent(w)?'time-urgent':''}">${resetUrgent(w)?'<span aria-hidden="true">⚠︎ </span>':''}${escape(left)}</strong>`;}
 function historyDate(t){if(!t)return L.t('dateMissing');const d=new Date(t),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`;}
 function previous(w){return w?.previous?`<div class="previous">${escape(L.t('previous',{value:w.previous.value!=null?extraValue(w.previous.value):value(w.previous.remaining),date:date(w.previous.capturedAt)}))}</div>`:'';}
 const changes=GlanceChanges.createTracker();
 function observe(data){for(const [id,s]of Object.entries(data)){if(s.status==='login'){changes.clear(id);continue}if(s.status!=='ready'||s.refreshing)continue;for(const w of s.windows||[])changes.observe(id,'window:'+w.label,value(w.remaining));for(const e of s.extras||[])changes.observe(id,'extra:'+e.label,e.value);}}
 function numeric(id,key,text){let i=0;return String(text??'').split(/(\d+(?:,\d{3})*(?:\.\d+)?)/g).map((part,index)=>{if(index%2===0)return escape(part);const end=changes.deadline(id,key,i++);return end?`<span class="changed-number" style="animation-delay:-${(Date.now()%1000)/1000}s">${escape(part)}</span>`:escape(part)}).join('');}
 function extras(data,id){const s=data[id],items=s?.extras||[];const entries=items.map(e=>{const urgent=!!e.expiresAt&&e.expiresAt-Date.now()<=7*86400000,bar=typeof e.barPercent==='number'?`<div class="track extra-track" aria-label="${escape(extraLabel(e.label)+' '+L.t('remaining',{value:value(e.barPercent)}))}"><i style="width:${percent(e.barPercent)??0}%"></i></div>`:'',resetAvailable=id==='chatgpt'&&e.label==='利用上限のリセット'&&/(?:利用可能|Available)\s*[1-9]\d*/.test(e.value),count=e.value.match(/\d+/)?.[0],shown=resetAvailable?`<a class="extra-action" href="${services.chatgpt.url}" target="_blank" rel="noopener" title="ChatGPT reset"><span aria-hidden="true">🎟</span> [${L.language()==='ja'?'利用可能':'Available'}]</a>${count?` ×${escape(count)}`:''}`:numeric(id,'extra:'+e.label,extraValue(e.value)),warning=urgent?'<span class="expiry-warning" title="Deadline within one week" aria-label="Deadline within one week">⚠︎</span> ':'';return `<div class="extra-row${urgent?' urgent':''}"><div class="extra-line"><span>${escape(extraLabel(e.label))}</span><b>${shown}</b></div>${bar}${e.detail?`<div class="extra-detail">${warning}${escape(extraDetail(e.detail))}</div>`:''}${previous(e)}</div>`});return `<div class="extras"><div class="extras-title">${escape(L.t('supplement'))}</div>`+(entries.length?entries.join(''):`<div class="extra-detail">${escape(L.t('creditMissing'))}</div>`)+(s?.capturedAt?`<div class="extra-detail">${escape(L.t('capturedAt',{date:date(s.capturedAt)}))}</div>`:'')+'</div>';}
 function extraLabel(value){if(L.language()==='ja')return value;return ({'クレジット':'Credits','追加クレジット':'Additional credits','使用クレジット':'Usage credits','利用権期限':'Access expiration','利用上限のリセット':'Usage-limit reset','クラウドセッションクレジット':'Cloud session credits','追加使用クレジット':'Extra usage credits','プロジェクトセットアップクレジット':'Project setup credits','Google AI 契約プラン':'Google AI plan'})[value]||value;}
 function extraValue(value){if(L.language()==='ja')return value;return displayText(value).replaceAll('残り','Remaining').replaceAll('無効','Disabled');}
 function extraDetail(value){if(L.language()==='ja')return value;return displayText(value).replaceAll('有効期限','Expiration').replaceAll('期限未取得','Expiration unavailable').replaceAll('期限','Expires').replaceAll('総額','Total').replaceAll('残り','Remaining').replace(/あと\s*(\d+)\s*日/g,'$1 days left').replaceAll('公式アカウントから取得','official account');}
 function age(s){if(!s?.capturedAt)return L.t('notAcquired');const n=Math.max(0,Math.floor((Date.now()-s.capturedAt)/1000));return n<60?L.t('secondsAgo',{n}):L.t('minutesAgo',{n:Math.floor(n/60)});}
 function historyRows(s,labelValue){const aliases=labelValue==='週間 (Work / Codex)'?['週間 (Work / Codex)','Work / Codex · 週間']:labelValue==='Work / Codex · 週間'?['Work / Codex · 週間','週間 (Work / Codex)']:[labelValue];return aliases.flatMap(key=>s?.history?.[key]||[]).sort((a,b)=>a.capturedAt-b.capturedAt).filter((r,i,rows)=>i===0||r.remaining!==rows[i-1]?.remaining).slice(-HISTORY_LIMIT);}
 function historyBox(s){const labels=[...(s?.windows||[]).map(w=>w.label),...Object.keys(s?.history||{})].filter((name,index,all)=>all.indexOf(name)===index),groups=labels.map(name=>{const rows=historyRows(s,name).reverse(),shown=label(name),lines=rows.map(r=>`${historyDate(r.capturedAt)}  ${L.t('remainingUsage',{value:value(r.remaining)})}`).join('\n');return `<section class="history-group"><div class="history-label">${escape(shown)} <span>${escape(L.t('items',{n:rows.length.toLocaleString(L.locale())}))}</span></div>${rows.length?`<textarea class="history-log" readonly wrap="off" aria-label="${escape(shown+' '+L.t('history'))}">${escape(lines)}</textarea>`:`<div class="history-empty">${escape(L.t('recordOnChange'))}</div>`}</section>`}).join('');return `<div class="history"><div class="extras-title">${escape(L.t('history'))}</div>${groups||`<div class="history-empty">${escape(L.t('historyEmpty'))}</div>`}</div>`;}
 function shownPlan(value){return !value||value==='未取得'?L.t('planMissing'):value;}
 function widget(data={}){return `<div class="widget-title">${escape(L.t('appTitle'))}</div>`+Object.entries(services).map(([id,p])=>{const s=data[id],windows=s?.windows||[],w=windows[0],v=percent(w?.remaining);return `<section class="widget-row" style="--color:${p.color}" aria-busy="${updating(s)}"><div class="widget-service"><span class="widget-mark">${p.mark}</span><span>${p.name}<small>${escape(shownPlan(s?.plan))}</small></span><em>${escape(status(s))}</em></div><div class="widget-primary"><b>${numeric(id,'window:'+w?.label,value(v))}</b><span>${escape(label(w?.label)||L.t('notAcquired'))}</span></div><div class="track primary-track"><i style="width:${v??0}%"></i></div><div class="widget-reset">${resetInside(w)}</div>${previous(w)}${windows.slice(1).map(x=>`<div class="widget-limit"><span>${escape(label(x.label))}</span><b>${numeric(id,'window:'+x.label,value(x.remaining))}</b></div><div class="track"><i style="width:${percent(x.remaining)??0}%"></i></div><div class="widget-reset${resetUrgent(x)?' time-urgent':''}">${escape(displayText(x.reset||L.t('resetMissing')))}</div>${previous(x)}`).join('')}${id==='chatgpt'?`<div class="widget-meta">${escape(L.t('chatUnsupported'))}</div>`:''}${extras(data,id)}${historyBox(s)}<div class="widget-age">${escape(age(s))}</div></section>`}).join('')+`<div class="widget-foot">${escape(L.t('officialEveryMinute'))}<br><small>${L.t('appTitleUpper')} v${APP_VERSION}<br>Copyright (C) 2026 NT MicroSystems,Inc.</small></div>`;}
 root.Glance={APP_VERSION,HISTORY_LIMIT,services,escape,fresh,percent,value,label,status,age,widget,previous,extras,historyBox,historyDate,resetInside,resetUrgent,updating,observe,numeric,changes,extraLabel,displayText,shownPlan};
})(globalThis);
