const {test}=require('node:test');const assert=require('node:assert/strict');const P=require('../extension/parser.js');
test('クレジットは総額を残高に取り違えず、金額と割合を区別',()=>{assert.equal(P.creditValue('$100中$39が残っています'),'残り $39 / $100');assert.equal(P.creditValue('24% 使用済み'),'残り 76%');assert.equal(P.creditValue('$0 プランの上限に達した場合'),'$0');assert.equal(P.creditValue('$12.50 remaining'),'残り $12.50');assert.equal(P.creditValue('読み込み中'),'未取得');});
function meter(label,value,text,parents=[]){let parent=null;for(const t of parents.toReversed())parent={innerText:t,parentElement:parent};return {getAttribute:k=>({'aria-label':label,'aria-valuenow':value,'aria-valuetext':text}[k]??null),parentElement:parent};}
function doc(elements=[],selectors={}){return {querySelectorAll:()=>elements,querySelector:s=>selectors[s],getElementById:()=>null};}
test('使用済みから残りへの変換・0と100・不正値',()=>{assert.equal(P.used('7% 使用済み'),93);assert.equal(P.used('0% used'),100);assert.equal(P.used('100% 使用中'),0);assert.equal(P.used('101% used'),null);assert.equal(P.used('24%'),null);assert.equal(P.remaining('残り0%'),0);assert.equal(P.remaining('71% remaining'),71);});
test('Claude: 製品別配分とクレジットは残量として採用しない',()=>{const d=doc([meter('現在のセッション','7','7% 使用済み',['','','7% 使用済み','現在のセッション\n4:00にリセットされます\n7% 使用済み']),meter('今週','10','10% 使用済み',['今週\n日曜にリセット\n10% 使用済み']),meter('Cowork','76','76%'),meter('含まれるクレジット','61','61% 使用済み')]);const w=P.parse(d,'claude');assert.equal(w.length,2);assert.equal(w[0].remaining,93);assert.equal(w[0].reset,'4:00にリセットされます');assert.equal(w[1].remaining,90);});
test('Gemini: 公式セレクタの現在・週を独立して読む',()=>{const w=P.parse(doc([],{ '[data-test-id="gxu-currently"]':{innerText:'現在の使用量\n1% 使用中\n6:25にリセット'},'[data-test-id="gxu-weekly"]':{innerText:'1 週間の上限\n10月1日の14:25にリセットされます\n12% 使用中'}}),'gemini');assert.deepEqual(w.map(x=>x.remaining),[99,88]);assert.equal(P.parse(doc(),'gemini').length,0);});
test('ChatGPT: リセット時間を枠の長さと取り違えずChatと区別',()=>{const w=P.parse(doc([meter('残りの利用可能量',null,null,['','5分後にリセット\n残り44%','5分後にリセット\n残り44%','5時間ごとの利用上限\n5分後にリセット\n残り44%']),meter('残りの利用可能量',null,null,['','6日23時間後にリセット\n残り93%','週ごとの利用上限\n6日23時間後にリセット\n残り93%'])]),'chatgpt');assert.equal(w.length,2);assert.equal(w[0].remaining,44);assert.equal(w[0].label,'Work / Codex · 5時間');assert.equal(w[1].label,'週間 (Work / Codex)');});
test('Claudeの未使用セッションは開始後にリセット時刻が決まることを表示',()=>{const w=P.parse(doc([meter('現在のセッション','0','0% 使用済み',['現在のセッション\n最初のメッセージから開始します\n0% 使用済み'])]),'claude');assert.equal(w[0].remaining,100);assert.equal(w[0].reset,'最初のメッセージから開始します');});
test('日本語のクレジット期限を日時へ変換',()=>{const time=P.expiryTime('11月5日16:59 JSTに期限切れ');assert.equal(new Date(time).getMonth(),10);assert.equal(new Date(time).getDate(),5);});
test('相対時間と当日時刻をresetAtへ変換する',()=>{const now=new Date(2026,8,28,8,0,0).getTime();assert.equal(P.resetTime('1日 2時間 3分後にリセット',now),now+(24*60+2*60+3)*60000);assert.equal(P.resetTime('in 2 hours 5 minutes',now),now+125*60000);const clock=P.resetTime('09:26にリセット',now);assert.equal(new Date(clock).getHours(),9);assert.equal(new Date(clock).getMinutes(),26);});
test('ChatGPTの利用上限リセット権・種別・期限を公式カードから取得',()=>{const expiry={textContent:'有効期限：10月23日',getAttribute:key=>key==='aria-label'?'有効期限: 10/23 5:10 JST':null},kind={textContent:'完全リセット（週間＋5 時間）'},tab={id:'available-tab',textContent:'利用可能 1'},panel={id:'available',getAttribute:key=>key==='aria-labelledby'?'available-tab':null,querySelector:selector=>selector.includes('有効期限')?expiry:null,querySelectorAll:()=>[kind,expiry]},page={querySelectorAll:selector=>selector==='[role="tab"]'?[tab]:selector==='[role="tabpanel"]'?[panel]:[],body:{innerText:'利用上限のリセット 利用可能 1'}};const reset=P.chatGPTReset(page);assert.equal(reset.label,'利用上限のリセット');assert.equal(reset.value,'利用可能 1');assert(reset.detail.includes('完全リセット'));assert(reset.detail.includes('有効期限'));assert.equal(new Date(reset.expiresAt).getMonth(),9);assert.equal(new Date(reset.expiresAt).getDate(),23);});
test('ChatGPTリセット権の属性なし可視テキストから10月30日の期限を取得',()=>{const kind={textContent:'CODEX 完全リセット（週間＋5 時間）',getAttribute:()=>null},expiry={textContent:'有効期限：10月30日',getAttribute:()=>null},tab={id:'available-tab',textContent:'利用可能 1'},panel={id:'available',innerText:'CODEX 完全リセット（週間＋5 時間） 有効期限：10月30日',getAttribute:key=>key==='aria-labelledby'?'available-tab':null,querySelector:()=>null,querySelectorAll:()=>[kind,expiry]},page={querySelectorAll:selector=>selector==='[role="tab"]'?[tab]:selector==='[role="tabpanel"]'?[panel]:[],body:{innerText:'利用上限のリセット 利用可能 1'}};const reset=P.chatGPTReset(page);assert.equal(new Date(reset.expiresAt).getMonth(),9);assert.equal(new Date(reset.expiresAt).getDate(),30);assert(reset.detail.includes('完全リセット'));assert(reset.detail.includes('有効期限'));});
test('ChatGPTリセット期限の原文を表示用に保持',()=>{const tab={id:'available-tab',textContent:'利用可能 1'},panel={id:'available',innerText:'完全リセット（週間＋5 時間） 有効期限：10月30日',getAttribute:key=>key==='aria-labelledby'?'available-tab':null,querySelectorAll:()=>[]},page={querySelectorAll:selector=>selector==='[role="tab"]'?[tab]:selector==='[role="tabpanel"]'?[panel]:[],body:{innerText:'利用上限のリセット 利用可能 1'}};const reset=P.chatGPTReset(page);assert.equal(reset.officialText,'完全リセット（週間＋5 時間） 有効期限：10月30日');});
test('タブ展開前も公式画面本文の件数と期限原文を採用',()=>{const page={querySelectorAll:()=>[],body:{innerText:'利用上限のリセット 利用可能 1 完全リセット（週間＋5 時間） 有効期限：10月30日'}};const reset=P.chatGPTReset(page);assert.equal(reset.value,'利用可能 1');assert.equal(reset.officialText,'完全リセット（週間＋5 時間） 有効期限：10月30日');});
test('ChatGPTのタブパネルが未展開でもページ可視文から期限を取得',()=>{const tab={id:'available-tab',textContent:'利用可能 1'},panel={id:'available',innerText:'',textContent:'',getAttribute:key=>key==='aria-labelledby'?'available-tab':null,querySelector:()=>null,querySelectorAll:()=>[]},page={querySelectorAll:selector=>selector==='[role="tab"]'?[tab]:selector==='[role="tabpanel"]'?[panel]:[],body:{innerText:'利用上限のリセット CODEX 完全リセット 有効期限：10月30日'}};const reset=P.chatGPTReset(page);assert.equal(new Date(reset.expiresAt).getMonth(),9);assert.equal(new Date(reset.expiresAt).getDate(),30);});
test('曖昧な利用枠と読み込み中は数値未取得',()=>{assert.deepEqual(P.parse(doc([meter('残りの利用可能量',null,null,['5時間ごとの利用上限\n週ごとの利用上限\nリセット\n残り50%'])]),'chatgpt'),[]);assert.deepEqual(P.parse(doc([meter('現在のセッション',null,'')]),'claude'),[]);});
test('各サービスの契約プランを公式画面上の短いラベルから読む',()=>{const el=textContent=>({textContent,getAttribute:()=>''});const make=value=>({querySelectorAll:s=>s.includes('tier-pill')?[el(value)]:[el(value)]});assert.equal(P.parsePlan(make('Plus'),'chatgpt'),'Plus');assert.equal(P.parsePlan(make('Max 20x'),'claude'),'Max 20x');assert.equal(P.parsePlan(make('Google AI Pro'),'gemini'),'Google AI Pro');assert.equal(P.parsePlan(make('設定'),'chatgpt'),'未取得');});
test('ChatGPTのclient-bootstrapから契約プランを読み、アップグレード広告は誤認しない',()=>{const script={textContent:JSON.stringify({session:{account:{planType:'plus'}}})};const bootstrap={querySelector:s=>s==='script#client-bootstrap'?script:null,querySelectorAll:()=>[],body:{innerText:'Upgrade to Pro'}};assert.equal(P.parsePlan(bootstrap,'chatgpt'),'Plus');const ad={querySelector:()=>null,querySelectorAll:()=>[],body:{innerText:'Upgrade to Pro'}};assert.equal(P.parsePlan(ad,'chatgpt'),'未取得');});
test('Geminiの現行名と旧称を契約プランへ正規化',()=>{assert.equal(P.normalizePlan('Google AI Ultra','gemini'),'Google AI Ultra');assert.equal(P.normalizePlan('Google One AI Premium','gemini'),'Google AI Pro');assert.equal(P.normalizePlan('Gemini Advanced','gemini'),'Google AI Pro');});
test('Geminiの契約プランを埋め込みJSONの現行キーから読む',()=>{assert.equal(P.planFromObject({account:{currentPlan:'Google AI Ultra'}},'gemini'),'Google AI Ultra');assert.equal(P.planFromObject({membershipTier:{productName:'Google One AI Premium'}},'gemini'),'Google AI Pro');assert.equal(P.planFromObject({paid_tier:'Gemini Advanced'},'gemini'),'Google AI Pro');});
test('Geminiの契約プランを短いアカウント表示内から読む',()=>{const candidate={textContent:'Google アカウント · Google AI Pro',getClientRects:()=>[{}]},page={querySelector:()=>null,querySelectorAll:selector=>selector.includes('a,button')?[candidate]:[],body:{innerText:''}};assert.equal(P.parsePlan(page,'gemini'),'Google AI Pro');});

test('ChatGPT reset expiry supports English month names and HTML date attributes',()=>{const tab={id:'available-tab',textContent:'Available 1'},expiry={textContent:'',getAttribute:key=>key==='aria-label'?'Expiration date: October 30, 2026 at 2:15 AM':null},panel={id:'available',innerText:'Reset entitlement Available 1',getAttribute:key=>key==='aria-labelledby'?'available-tab':null,querySelector:()=>null,querySelectorAll:selector=>selector.includes('[aria-label]')?[expiry]:[]},page={querySelectorAll:selector=>selector==='[role="tab"]'?[tab]:selector==='[role="tabpanel"]'?[panel]:[],body:{innerText:'Usage limit resets Available 1'}};const reset=P.chatGPTReset(page);assert.equal(new Date(reset.expiresAt).getMonth(),9);assert.equal(new Date(reset.expiresAt).getDate(),30);assert.equal(new Date(reset.expiresAt).getHours(),2);assert.equal(new Date(reset.expiresAt).getMinutes(),15);});
test('期限用data属性のepoch秒・ミリ秒を日時へ正規化',()=>{const seconds=Date.UTC(2026,9,30,2,15)/1000,millis=seconds*1000;assert.equal(P.expiryTime(String(seconds)),millis);assert.equal(P.expiryTime(String(millis)),millis);});
test('期限属性のepochだけを採用し、無関係なaria-label数値を期限にしない',()=>{const time=Date.UTC(2026,9,30,2,15),tab={id:'available-tab',textContent:'Available 1'},epoch={getAttribute:key=>key==='data-expires-at'?String(time):null},id={getAttribute:key=>key==='aria-label'?'1793345700000':null},panel={id:'available',innerText:'Reset Available 1',getAttribute:key=>key==='aria-labelledby'?'available-tab':null,querySelector:()=>null,querySelectorAll:selector=>selector.includes('data-expires-at')?[epoch,id]:[]},page={querySelectorAll:selector=>selector==='[role="tab"]'?[tab]:selector==='[role="tabpanel"]'?[panel]:[],body:{innerText:'Usage limit resets Available 1'}};assert.equal(P.chatGPTReset(page).expiresAt,time);const onlyId={...panel,innerText:'Reset Available 1',querySelectorAll:selector=>selector.includes('data-expires-at')?[id]:[]},withoutExpiry=P.chatGPTReset({...page,querySelectorAll:selector=>selector==='[role="tab"]'?[tab]:selector==='[role="tabpanel"]'?[onlyId]:[],body:{innerText:'Usage limit resets Available 1'}});assert.equal(withoutExpiry.expiresAt,null);});
