const {test}=require('node:test');const assert=require('node:assert/strict');const S=require('../extension/state.js');
const snap=(a,b=90)=>({status:'ready',windows:[{label:'session',remaining:a},{label:'week',remaining:b}],extras:[{label:'credits',value:'$39'}]});
test('更新開始と取得失敗でも直前値・取得日時を保持',()=>{const old=S.accept({},snap(80),1000),loading=S.loading(old,2000);assert.equal(loading.windows[0].remaining,80);assert.equal(loading.capturedAt,1000);assert.equal(loading.refreshing,true);const failed=S.accept(loading,{status:'unavailable'},3000);assert.equal(failed.windows[0].remaining,80);assert.equal(failed.capturedAt,1000);assert.equal(failed.refreshing,false);});
test('変更時の前回値・直前の取得日時を枠別に保存し、同値では履歴保持',()=>{let s=S.accept({},snap(80),1000);s=S.accept(S.loading(s),snap(80),2000);assert.equal(s.windows[0].previous,undefined);s=S.accept(S.loading(s),snap(70),3000);assert.deepEqual(s.windows[0].previous,{remaining:80,capturedAt:2000});assert.equal(s.windows[1].previous,undefined);s=S.accept(s,snap(70),4000);assert.equal(s.windows[0].previous.capturedAt,2000);s=S.accept(s,snap(65,85),5000);assert.deepEqual(s.windows[0].previous,{remaining:70,capturedAt:4000});assert.deepEqual(s.windows[1].previous,{remaining:90,capturedAt:4000});});
test('ログアウト後は値・クレジット・履歴を残さない',()=>{const s=S.accept(S.accept({},snap(80),1000),{status:'login'},2000);assert.deepEqual(s.windows,[]);assert.deepEqual(s.extras,[]);assert.equal(s.capturedAt,null);});
test('クレジット変化とゼロ残量',()=>{const s=S.accept({},snap(1),1000),n=snap(0);n.extras[0].value='$0';const r=S.accept(s,n,2000);assert.equal(r.windows[0].remaining,0);assert.deepEqual(r.extras[0].previous,{value:'$39',capturedAt:1000});});
test('一時的に契約プランを取得できなくても既知の値を保持',()=>{const first={...snap(80),plan:'Pro'},missing={...snap(79),plan:'未取得'};const result=S.accept(S.accept({},first,1000),missing,2000);assert.equal(result.plan,'Pro');});
test('公式画面から取得したChatGPTリセット期限をAPI更新後も期限まで保持',()=>{const expiry=500000,first={...snap(80),extras:[{label:'利用上限のリセット',value:'利用可能 1',detail:'有効期限 2026/10/23',expiresAt:expiry,observedAt:1000}]},api={...snap(79),extras:[]};const result=S.accept(S.accept({},first,1000),api,2000);assert.equal(result.extras[0].expiresAt,expiry);assert.equal(result.extras[0].label,'利用上限のリセット');});
test('同じリセット権のAPI結果に期限がなくても既知の期限を補完',()=>{const expiry=500000,first={...snap(80),extras:[{label:'利用上限のリセット',value:'利用可能 1',detail:'有効期限あり',expiresAt:expiry}]},api={...snap(79),extras:[{label:'利用上限のリセット',value:'利用可能 1',detail:'期限未取得'}]};const result=S.accept(S.accept({},first,1000),api,2000);assert.equal(result.extras[0].expiresAt,expiry);assert.equal(result.extras[0].detail,'有効期限あり');});
